export const TYPING_WORDS = [
  "about", "above", "accept", "across", "action", "active", "actual", "added",
  "adjust", "advice", "after", "again", "agree", "ahead", "allow", "almost",
  "alone", "along", "already", "also", "always", "among", "amount", "ancient",
  "angle", "another", "answer", "anyone", "appear", "apply", "around", "arrive",
  "article", "aside", "ask", "aspect", "assert", "assign", "assume", "attack",
  "attend", "author", "autumn", "available", "average", "avoid", "award", "aware",
  "away", "balance", "bank", "base", "basic", "beach", "become", "before",
  "begin", "behind", "believe", "below", "benefit", "beside", "better", "between",
  "beyond", "binary", "bird", "birth", "black", "blank", "block", "board",
  "border", "bottle", "bottom", "branch", "brave", "bread", "break", "bridge",
  "brief", "bright", "bring", "broad", "broken", "brother", "brown", "build",
  "button", "buyer", "cable", "camera", "campus", "cancel", "candle", "canvas",
  "capable", "capital", "capture", "carbon", "career", "careful", "carry", "castle",
  "catch", "cause", "center", "certain", "chain", "chair", "chance", "change",
  "charge", "chart", "check", "cheese", "choice", "choose", "circle", "city",
  "claim", "class", "clean", "clear", "client", "climate", "clock", "close",
  "cloud", "coach", "coast", "code", "coffee", "collect", "color", "column",
  "combine", "come", "common", "company", "compare", "complete", "complex", "compute",
  "concept", "confirm", "connect", "consider", "contain", "content", "control", "convert",
  "cookie", "copper", "corner", "correct", "cost", "cotton", "could", "count",
  "course", "cover", "craft", "create", "credit", "crime", "cross", "crowd",
  "crystal", "culture", "current", "custom", "cycle", "daily", "damage", "dance",
  "danger", "data", "date", "deal", "decade", "decide", "deep", "default",
  "defend", "define", "degree", "delay", "deliver", "demand", "depend", "design",
  "detail", "detect", "device", "differ", "digital", "direct", "discuss", "display",
  "distance", "divide", "doctor", "document", "domain", "double", "draft", "drama",
  "draw", "dream", "drive", "drop", "during", "each", "early", "earth",
  "ease", "east", "easy", "economy", "edge", "edit", "effect", "effort",
  "either", "elect", "element", "else", "email", "emerge", "emotion", "employ",
  "empty", "enable", "end", "energy", "engine", "enjoy", "enough", "enter",
  "entire", "entry", "equal", "error", "escape", "essay", "estate", "event",
  "every", "exact", "example", "except", "exchange", "exist", "expand", "expect",
  "expert", "export", "extend", "extra", "face", "fact", "factor", "fail",
  "fair", "faith", "fall", "family", "famous", "farm", "fast", "father",
  "favor", "fear", "feature", "feed", "feel", "field", "figure", "file",
  "fill", "film", "final", "find", "fine", "finger", "finish", "fire",
  "first", "fiscal", "fish", "fit", "five", "fix", "flag", "flash",
  "flat", "flight", "float", "floor", "flow", "flower", "fly", "focus",
  "follow", "food", "foot", "force", "forest", "forget", "form", "formal",
  "format", "former", "found", "frame", "free", "fresh", "friend", "from",
  "front", "fruit", "full", "fun", "function", "fund", "funny", "future",
  "gain", "game", "garden", "gate", "gather", "general", "gentle", "get",
  "giant", "gift", "give", "glass", "global", "goal", "gold", "good",
  "govern", "grade", "grand", "grant", "graph", "grass", "great", "green",
  "ground", "group", "grow", "growth", "guard", "guess", "guest", "guide",
  "habit", "half", "hall", "hand", "handle", "happen", "happy", "hard",
  "have", "head", "health", "hear", "heart", "heat", "heavy", "height",
  "help", "here", "hide", "high", "hill", "history", "hold", "home",
  "hope", "horse", "host", "hotel", "hour", "house", "human", "idea",
  "image", "impact", "import", "improve", "include", "income", "increase", "indeed",
  "index", "indoor", "industry", "inform", "initial", "input", "inside", "insight",
  "install", "instead", "intact", "intend", "interest", "into", "invest", "invite",
  "iron", "island", "issue", "item", "itself", "join", "joint", "joke",
  "judge", "jump", "just", "keep", "key", "kick", "kind", "king",
  "kitchen", "knee", "knife", "know", "label", "labor", "lack", "lake",
  "land", "language", "large", "last", "late", "later", "laugh", "launch",
  "law", "layer", "lead", "learn", "least", "leave", "left", "legal",
  "lemon", "length", "less", "letter", "level", "library", "light", "like",
  "limit", "line", "link", "list", "listen", "little", "live", "load",
  "local", "locate", "lock", "logic", "long", "look", "loop", "lose",
  "loss", "lot", "loud", "love", "low", "lower", "luck", "lunch",
  "machine", "magic", "mail", "main", "major", "make", "manage", "manner",
  "many", "map", "margin", "mark", "market", "master", "match", "material",
  "matter", "maybe", "mean", "measure", "media", "meet", "member", "memory",
  "mention", "menu", "mere", "message", "metal", "method", "middle", "might",
  "mile", "milk", "mind", "mine", "minor", "minute", "miss", "mission",
  "mixed", "mobile", "model", "modern", "moment", "money", "monitor", "month",
  "mood", "moon", "more", "morning", "most", "mother", "motion", "motor",
  "mount", "mouse", "mouth", "move", "movie", "much", "music", "must",
  "name", "nation", "native", "nature", "near", "nearly", "need", "network",
  "never", "new", "news", "next", "nice", "night", "nine", "noise",
  "none", "normal", "north", "note", "notice", "novel", "number", "nurse",
  "object", "occur", "ocean", "offer", "office", "often", "oil", "okay",
  "old", "once", "online", "only", "open", "option", "orange", "order",
  "other", "output", "outside", "over", "owner", "pace", "pack", "page",
  "pain", "paint", "pair", "panel", "paper", "parent", "park", "part",
  "party", "pass", "past", "path", "pattern", "pause", "pay", "peace",
  "people", "percent", "perfect", "perform", "period", "person", "phase", "phone",
  "photo", "phrase", "pick", "picture", "piece", "place", "plan", "plant",
  "plate", "play", "please", "plenty", "pocket", "point", "police", "policy",
  "pond", "pool", "poor", "popular", "port", "pose", "position", "possible",
  "post", "power", "practice", "prefer", "prepare", "present", "press", "pretty",
  "prevent", "price", "pride", "prime", "print", "prior", "private", "prize",
  "problem", "process", "produce", "product", "profit", "program", "project", "promise",
  "proof", "proper", "protect", "prove", "provide", "public", "pull", "pure",
  "purple", "purpose", "push", "put", "quality", "quarter", "queen", "question",
  "quick", "quiet", "quite", "quote", "race", "radio", "rain", "raise",
  "range", "rank", "rapid", "rare", "rate", "rather", "reach", "read",
  "ready", "real", "reason", "recall", "receive", "recent", "record", "reduce",
  "refer", "region", "relate", "remain", "remember", "remove", "repeat", "report",
  "request", "require", "research", "resource", "respect", "respond", "rest", "result",
  "return", "reveal", "review", "reward", "rich", "ride", "right", "ring",
  "rise", "risk", "river", "road", "robot", "rock", "role", "roll",
  "room", "root", "rope", "rough", "round", "route", "row", "royal",
  "rule", "run", "rural", "safe", "sail", "salad", "sale", "salt",
  "same", "sample", "sand", "save", "scale", "scene", "school", "science",
  "score", "screen", "script", "search", "season", "seat", "second", "secret",
  "section", "secure", "see", "seed", "seek", "seem", "select", "self",
  "sell", "send", "sense", "series", "serve", "service", "set", "settle",
  "seven", "several", "shadow", "shake", "shall", "shape", "share", "sharp",
  "sheet", "shell", "shift", "shine", "ship", "shirt", "shock", "shoot",
  "shop", "short", "should", "shoulder", "show", "side", "sight", "sign",
  "signal", "silent", "silver", "simple", "since", "sing", "single", "sister",
  "sit", "site", "size", "skill", "skin", "sky", "sleep", "slide",
  "slight", "slow", "small", "smart", "smell", "smile", "smoke", "smooth",
  "snake", "snow", "soft", "soil", "solar", "solid", "solve", "some",
  "song", "soon", "sort", "sound", "source", "south", "space", "spare",
  "speak", "special", "speed", "spend", "spirit", "split", "sport", "spot",
  "spread", "spring", "square", "stable", "staff", "stage", "stand", "star",
  "start", "state", "station", "stay", "steady", "steel", "step", "stick",
  "still", "stock", "stone", "stop", "store", "storm", "story", "straight",
  "strange", "street", "strong", "student", "study", "stuff", "style", "subject",
  "success", "such", "sudden", "sugar", "suggest", "summer", "sun", "super",
  "supply", "support", "sure", "surface", "system", "table", "take", "talk",
  "tall", "target", "task", "taste", "teach", "team", "tell", "tend",
  "term", "test", "text", "than", "thank", "that", "their", "them",
  "then", "there", "these", "they", "thick", "thin", "thing", "think",
  "third", "this", "those", "though", "thought", "three", "through", "throw",
  "thumb", "ticket", "tide", "tight", "time", "tiny", "title", "today",
  "together", "token", "tomato", "tone", "tool", "tooth", "top", "topic",
  "total", "touch", "toward", "tower", "town", "track", "trade", "traffic",
  "train", "travel", "treat", "tree", "trend", "trial", "tribe", "trick",
  "trip", "true", "trust", "truth", "try", "tube", "turn", "twelve",
  "twenty", "twice", "type", "under", "union", "unique", "unit", "unite",
  "until", "upon", "upper", "urban", "urgent", "usage", "use", "useful",
  "usual", "value", "various", "vast", "vector", "vendor", "verse", "version",
  "very", "vessel", "video", "view", "village", "virus", "visit", "visual",
  "voice", "volume", "vote", "wage", "wait", "walk", "wall", "want",
  "warm", "warn", "wash", "waste", "watch", "water", "wave", "way",
  "weak", "wealth", "wear", "weather", "week", "weight", "welcome", "well",
  "west", "what", "wheel", "when", "where", "which", "while", "white",
  "whole", "whose", "wide", "wife", "wild", "will", "win", "wind",
  "window", "wine", "wing", "winter", "wire", "wise", "wish", "with",
  "within", "without", "woman", "wonder", "wood", "word", "work", "world",
  "worry", "worth", "would", "write", "wrong", "yard", "year", "yellow",
  "yes", "yesterday", "yet", "young", "your", "youth", "zone",
] as const;

export const TYPING_SENTENCES = [
  "clean code is easier to change than clever code",
  "practice builds speed but accuracy builds trust",
  "a steady rhythm often beats frantic bursts of typing",
  "short words keep the fingers moving without heavy strain",
  "focus on the next letter instead of the whole page",
  "quiet practice sessions improve muscle memory over time",
  "clear goals help you measure progress week after week",
  "typing is a craft of attention as much as speed",
  "small daily sessions beat occasional long marathons",
  "keep your wrists relaxed and your shoulders low",
  "read a few words ahead while your hands stay on the keys",
  "errors teach more when you notice them immediately",
  "consistency matters more than a single high score",
  "tools work best when the interface stays out of the way",
  "simple sentences reveal habits that fancy text can hide",
] as const;

export const TYPING_NUMBERS = [
  "2", "3", "4", "5", "7", "8", "9", "10", "12", "15", "20", "25", "30", "42", "50", "64", "75", "100", "128", "256",
] as const;

export const TYPING_PUNCT = [",", ".", "!", "?", ";", ":"] as const;
