import type { ToolDefinition } from "./types";

function tool(
  partial: Omit<ToolDefinition, "route" | "status"> & {
    status?: ToolDefinition["status"];
  },
): ToolDefinition {
  return {
    ...partial,
    route: `/tools/${partial.slug}`,
    status: partial.status ?? "available",
  };
}

/** Twenty content/dev generators — Generators category expansion */
export const contentGeneratorTools: ToolDefinition[] = [
  tool({
    id: "username-generator",
    name: "Username Generator",
    slug: "username-generator",
    category: "generators",
    exactPrimaryKeyword: "username generator",
    aliases: ["random username","generate username"],
    description: "Generate random usernames from adjective/noun patterns, optional numbers, and separators — all in your browser with local word lists.",
    shortDescription: "Generate random usernames from local word rules.",
    icon: "text",
    keywords: ["username generator","random username generator","username maker"],
    popular: false,
    new: true,
    supportedFormats: ["Text usernames"],
    relatedToolIds: ["random-string-generator","temporary-email-generator","uuid-generator","password-generator"],
    seoTitle: "Username Generator — Create Random Usernames | Tool Base",
    seoDescription: "Generate random usernames online with Tool Base. Choose style, length, numbers, and quantity — no account required.",
    h1: "Username Generator",
    intro: "Create random username ideas from local word lists and simple rules. Choose style, length, separators, and quantity, then copy or download the results. This Username Generator does not check platform availability.",
    convertHeading: "Generate Random Usernames Online",
    howToHeading: "How the Username Generator Works",
    featuresHeading: "Username Generator Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Adjective + noun and short styles","Optional numbers and separators","Batch generation with quantity limits","Copy one, copy all, or download TXT","Local word lists — no AI API"],
    howToSteps: [
      { title: "Choose Username Options", description: "Pick style, length, numbers, separator, and quantity." },
      { title: "Generate Usernames", description: "Create a fresh batch instantly in your browser." },
      { title: "Copy or Download", description: "Copy results or download a TXT file." },
    ],
    faq: [
      { question: "Are usernames guaranteed available?", answer: "No. This tool only generates ideas. Availability depends on each platform." },
      { question: "Does it use an AI API?", answer: "No. Usernames are built from local word lists and rules." },
      { question: "Can I generate many at once?", answer: "Yes, up to a safe maximum so the browser stays responsive." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["Text usernames"],
    examples: [
      {
        title: "Adjective + noun + number",
        description: "Static worked example — not your live result.",
        input: "style adj-noun-number, quantity 3",
        output: "bluefox27\\nswiftpixel8\\ncloudnova42",
      },
    ],
  }),
  tool({
    id: "business-name-generator",
    name: "Business Name Generator",
    slug: "business-name-generator",
    category: "generators",
    exactPrimaryKeyword: "business name generator",
    aliases: ["company name ideas","brand name generator"],
    description: "Generate business name ideas from industry, keyword, and style templates. Results are creative suggestions only — not trademark or domain checks.",
    shortDescription: "Generate business name ideas from templates.",
    icon: "text",
    keywords: ["business name generator","company name generator","startup name generator"],
    popular: false,
    new: true,
    supportedFormats: ["Text names"],
    relatedToolIds: ["username-generator","blog-title-generator","url-slug-generator","random-string-generator"],
    seoTitle: "Business Name Generator — Brand Name Ideas | Tool Base",
    seoDescription: "Generate business name ideas online with Tool Base. Combine industry, keyword, and style templates for creative brand suggestions.",
    h1: "Business Name Generator",
    intro: "Brainstorm business name ideas with industry, keyword, style, and optional prefix or suffix controls. The Business Name Generator produces ideas only and does not check trademarks or domain availability.",
    convertHeading: "Generate Business Name Ideas",
    howToHeading: "How the Business Name Generator Works",
    featuresHeading: "Business Naming Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Modern, premium, tech, and more styles","Keyword and industry inputs","Optional prefixes and suffixes","Batch idea lists with copy/download","Clear non-availability disclaimer"],
    howToSteps: [
      { title: "Describe the Business", description: "Enter industry, keyword, style, and length preferences." },
      { title: "Generate Names", description: "Create a list of idea names instantly." },
      { title: "Copy Ideas", description: "Copy one name or the full list for brainstorming." },
    ],
    faq: [
      { question: "Does this generator check trademark availability?", answer: "No. It does not perform trademark or legal availability checks." },
      { question: "Are domains checked?", answer: "No. Domain availability is not verified." },
      { question: "Can I use a generated name commercially?", answer: "Treat results as ideas and verify trademarks, domains, and local rules yourself." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["Text names"],
    examples: [
      {
        title: "Modern style idea",
        description: "Static worked example — not your live result.",
        input: "keyword nova, style modern",
        output: "Novaly / Novaify style combinations",
      },
    ],
  }),
  tool({
    id: "blog-title-generator",
    name: "Blog Title Generator",
    slug: "blog-title-generator",
    category: "generators",
    exactPrimaryKeyword: "blog title generator",
    aliases: ["blog headline ideas","title ideas generator"],
    description: "Generate blog title ideas from topic, keyword, audience, and tone using local structured templates — not an AI writing service.",
    shortDescription: "Generate blog title ideas from templates.",
    icon: "text",
    keywords: ["blog title generator","article title generator","headline generator"],
    popular: false,
    new: true,
    supportedFormats: ["Text titles"],
    relatedToolIds: ["hashtag-generator","url-slug-generator","meta-tags-generator","lorem-ipsum-generator"],
    seoTitle: "Blog Title Generator — Headline Ideas Online | Tool Base",
    seoDescription: "Generate blog title ideas with Tool Base using topic, keyword, audience, and tone templates. Fast, local, and free.",
    h1: "Blog Title Generator",
    intro: "Turn a topic into useful headline ideas with the Blog Title Generator. Titles come from structured local templates such as “How to…” and “Complete Guide” patterns — not from an AI model.",
    convertHeading: "Generate Blog Title Ideas",
    howToHeading: "How the Blog Title Generator Works",
    featuresHeading: "Title Idea Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Topic, keyword, audience, and tone inputs","Multiple title templates","Quantity limits for safe batching","Copy all titles at once","Clearly local template generation"],
    howToSteps: [
      { title: "Enter Topic Details", description: "Provide topic, keyword, audience, and tone." },
      { title: "Generate Titles", description: "Create a batch of title ideas instantly." },
      { title: "Copy All", description: "Copy the full list into your editorial draft." },
    ],
    faq: [
      { question: "Are these AI-generated titles?", answer: "No. Titles are assembled from local templates and your inputs." },
      { question: "Can I control tone?", answer: "Yes. Choose practical, friendly, expert, or bold framing." },
      { question: "Is there a quantity limit?", answer: "Yes, to keep generation fast and avoid freezing the browser." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["Text titles"],
    examples: [
      {
        title: "Guide pattern",
        description: "Static worked example — not your live result.",
        input: "topic improve focus",
        output: "The Complete Guide to improve focus",
      },
    ],
  }),
  tool({
    id: "hashtag-generator",
    name: "Hashtag Generator",
    slug: "hashtag-generator",
    category: "generators",
    exactPrimaryKeyword: "hashtag generator",
    aliases: ["generate hashtags","social hashtags"],
    description: "Generate relevant-looking hashtags from a topic using curated local modifiers. This tool does not show live trending scores or popularity counts.",
    shortDescription: "Generate hashtags from a topic using local rules.",
    icon: "text",
    keywords: ["hashtag generator","instagram hashtag generator","hashtag maker"],
    popular: false,
    new: true,
    supportedFormats: ["Hashtags"],
    relatedToolIds: ["blog-title-generator","username-generator","url-slug-generator","random-string-generator"],
    seoTitle: "Hashtag Generator — Create Hashtags Online | Tool Base",
    seoDescription: "Generate hashtags from a topic with Tool Base. Local rules create broad or niche tags without fake trending claims.",
    h1: "Hashtag Generator",
    intro: "Enter a topic and generate hashtags with broad or niche modes. The Hashtag Generator uses local combinations and does not claim real-time trending status or popularity counts.",
    convertHeading: "Generate Hashtags Online",
    howToHeading: "How the Hashtag Generator Works",
    featuresHeading: "Hashtag Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Topic-based generation","Broad and niche modes","Optional platform flavor","Copy hashtags in one click","No fake popularity metrics"],
    howToSteps: [
      { title: "Enter a Topic", description: "Type a keyword or subject for your posts." },
      { title: "Generate Hashtags", description: "Create a list from local rules instantly." },
      { title: "Copy Hashtags", description: "Paste the tags into your caption draft." },
    ],
    faq: [
      { question: "Are these trending hashtags?", answer: "No. The tool does not fetch live trending data." },
      { question: "Why are there no popularity counts?", answer: "Fake popularity would be misleading, so counts are omitted." },
      { question: "Can I generate niche tags?", answer: "Yes. Switch to niche mode for more specific combinations." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["Hashtags"],
    examples: [
      {
        title: "Topic gardening",
        description: "Static worked example — not your live result.",
        input: "gardening, quantity 5",
        output: "#gardening #gardeningtips ...",
      },
    ],
  }),
  tool({
    id: "url-slug-generator",
    name: "URL Slug Generator",
    slug: "url-slug-generator",
    category: "generators",
    exactPrimaryKeyword: "url slug generator",
    aliases: ["slugify text","seo slug generator"],
    description: "Convert titles and phrases into clean URL slugs with lowercase letters, separators, optional stop-word removal, and max length controls.",
    shortDescription: "Convert text into clean URL slugs.",
    icon: "text",
    keywords: ["url slug generator","slug generator","permalink generator"],
    popular: false,
    new: true,
    supportedFormats: ["URL slug"],
    relatedToolIds: ["utm-url-builder","meta-tags-generator","blog-title-generator","sitemap-xml-generator"],
    seoTitle: "URL Slug Generator — Create Clean Permalinks | Tool Base",
    seoDescription: "Convert text into clean URL slugs with Tool Base. Lowercase, strip punctuation, choose separators, and copy instantly.",
    h1: "URL Slug Generator",
    intro: "Transform headings into clean, URL-safe slugs. The URL Slug Generator lowercases text, removes punctuation, collapses separators, and can trim stop words or enforce a max length.",
    convertHeading: "Generate a URL Slug Online",
    howToHeading: "How the URL Slug Generator Works",
    featuresHeading: "Slug Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Lowercase and punctuation cleanup","Dash or underscore separators","Optional stop-word removal","Max length control","Instant copy"],
    howToSteps: [
      { title: "Enter Text to Slugify", description: "Paste a title or phrase." },
      { title: "Choose Options", description: "Pick separator, stop words, and max length." },
      { title: "Copy Slug", description: "Copy the generated slug into your CMS." },
    ],
    faq: [
      { question: "Does it support Unicode?", answer: "Accented characters are normalized where practical before slugifying." },
      { question: "Can I keep underscores?", answer: "Yes. Choose underscore as the separator." },
      { question: "What about stop words?", answer: "Optionally remove common words like “the” and “and”." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["URL slug"],
    examples: [
      {
        title: "Title to slug",
        description: "Static worked example — not your live result.",
        input: "The Best Online Image Tools in 2026!",
        output: "the-best-online-image-tools-in-2026",
      },
    ],
  }),
  tool({
    id: "utm-url-builder",
    name: "UTM URL Builder",
    slug: "utm-url-builder",
    category: "generators",
    exactPrimaryKeyword: "utm url builder",
    aliases: ["utm link generator","utm parameter builder"],
    description: "Build tracking URLs with utm_source, utm_medium, utm_campaign, and optional term/content using proper URL encoding that preserves existing query parameters.",
    shortDescription: "Build campaign URLs with UTM parameters.",
    icon: "text",
    keywords: ["utm url builder","utm builder","campaign url builder"],
    popular: false,
    new: true,
    supportedFormats: ["URL"],
    relatedToolIds: ["url-slug-generator","meta-tags-generator","open-graph-generator","sitemap-xml-generator"],
    seoTitle: "UTM URL Builder — Create Campaign Tracking Links | Tool Base",
    seoDescription: "Build UTM campaign URLs with Tool Base. Add source, medium, campaign, term, and content with correct encoding.",
    h1: "UTM URL Builder",
    intro: "Create campaign tracking links with the UTM URL Builder. Enter a base URL and UTM fields; Tool Base uses the URL and URLSearchParams APIs so existing query parameters stay intact and values are encoded safely.",
    convertHeading: "Build a UTM Tracking URL",
    howToHeading: "How the UTM URL Builder Works",
    featuresHeading: "UTM Builder Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["utm_source, medium, campaign, term, content","Preserves existing query parameters","Proper URL encoding","Copy the final URL","No account required"],
    howToSteps: [
      { title: "Enter Campaign Parameters", description: "Provide base URL and UTM fields." },
      { title: "Generate URL", description: "Build an encoded tracking URL instantly." },
      { title: "Copy URL", description: "Paste the link into ads or email tools." },
    ],
    faq: [
      { question: "What does utm_source mean?", answer: "It identifies where traffic comes from, such as google or newsletter." },
      { question: "Will existing query params be lost?", answer: "No. The builder merges UTM parameters into the existing search string." },
      { question: "Is encoding handled automatically?", answer: "Yes. Values are set through URLSearchParams." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["URL"],
    examples: [
      {
        title: "Basic campaign",
        description: "Static worked example — not your live result.",
        input: "https://example.com + google/cpc/spring",
        output: "https://example.com/?utm_source=google&utm_medium=cpc&utm_campaign=spring",
      },
    ],
  }),
  tool({
    id: "color-palette-generator",
    name: "Color Palette Generator",
    slug: "color-palette-generator",
    category: "generators",
    exactPrimaryKeyword: "color palette generator",
    aliases: ["generate color palette","color scheme generator"],
    description: "Generate useful HEX color palettes with adjustable size, lockable swatches, and one-click copy — all in the browser.",
    shortDescription: "Generate HEX color palettes with lockable swatches.",
    icon: "text",
    keywords: ["color palette generator","color palette maker","hex palette generator"],
    popular: false,
    new: true,
    supportedFormats: ["HEX colors"],
    relatedToolIds: ["css-gradient-generator","css-box-shadow-generator","css-border-radius-generator","css-clamp-generator"],
    seoTitle: "Color Palette Generator — Create HEX Palettes | Tool Base",
    seoDescription: "Generate color palettes online with Tool Base. Create HEX swatches, lock colors, and copy the full palette instantly.",
    h1: "Color Palette Generator",
    intro: "Build a color palette for UI and design drafts. The Color Palette Generator creates HEX swatches you can lock and regenerate around, then copy as a list.",
    convertHeading: "Generate a Color Palette Online",
    howToHeading: "How the Color Palette Generator Works",
    featuresHeading: "Color Palette Tips",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Design Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["3–8 color palettes","Lock individual swatches","HEX values with copy","Readable default saturation ranges","Instant regenerate"],
    howToSteps: [
      { title: "Choose Your Palette Size", description: "Select how many colors to generate." },
      { title: "Generate a New Palette", description: "Create swatches and lock any keepers." },
      { title: "Copy Your Colors", description: "Copy the HEX list into your design tools." },
    ],
    faq: [
      { question: "Are colors accessibility-checked?", answer: "Palettes aim for readable mid-range lightness; always verify contrast for text use." },
      { question: "Can I lock a color?", answer: "Yes. Lock swatches before regenerating the rest." },
      { question: "What format is outputted?", answer: "HEX values such as #0f766e." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["HEX colors"],
    examples: [
      {
        title: "Five-color palette",
        description: "Static worked example — not your live result.",
        input: "size 5",
        output: "#.....\\n#.....",
      },
    ],
  }),
  tool({
    id: "css-gradient-generator",
    name: "CSS Gradient Generator",
    slug: "css-gradient-generator",
    category: "generators",
    exactPrimaryKeyword: "css gradient generator",
    aliases: ["css background gradient","radial gradient generator"],
    description: "Generate linear or radial CSS gradients with color stops, angle or position controls, live preview, and copyable CSS.",
    shortDescription: "Generate CSS linear and radial gradients with live preview.",
    icon: "text",
    keywords: ["css gradient generator","gradient generator","linear gradient generator"],
    popular: false,
    new: true,
    supportedFormats: ["CSS"],
    relatedToolIds: ["color-palette-generator","css-box-shadow-generator","css-border-radius-generator","css-clamp-generator"],
    seoTitle: "CSS Gradient Generator — Linear & Radial CSS | Tool Base",
    seoDescription: "Generate CSS gradients with Tool Base. Configure linear or radial backgrounds, preview live, and copy the CSS.",
    h1: "CSS Gradient Generator",
    intro: "Design a background gradient and copy the CSS. The CSS Gradient Generator supports linear and radial modes with multiple color stops and a scoped live preview.",
    convertHeading: "Generate a CSS Gradient Online",
    howToHeading: "How the CSS Gradient Generator Works",
    featuresHeading: "Gradient Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Design Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Linear and radial modes","Angle and position controls","Multiple color stops","Live preview","Copy CSS output"],
    howToSteps: [
      { title: "Configure Gradient", description: "Choose type, colors, and angle or position." },
      { title: "Generate CSS", description: "Create the background declaration." },
      { title: "Copy CSS", description: "Paste into your stylesheet." },
    ],
    faq: [
      { question: "Does the preview match the CSS?", answer: "Yes. The preview uses the same generated background value." },
      { question: "Can I use three colors?", answer: "Yes. Enable the third color stop." },
      { question: "Is the CSS injected into the whole site?", answer: "No. Preview styles are scoped to the preview box." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["CSS"],
    examples: [
      {
        title: "Linear gradient",
        description: "Static worked example — not your live result.",
        input: "90deg, teal to sky",
        output: "background: linear-gradient(90deg, #0f766e, #38bdf8);",
      },
    ],
  }),
  tool({
    id: "css-box-shadow-generator",
    name: "CSS Box Shadow Generator",
    slug: "css-box-shadow-generator",
    category: "generators",
    exactPrimaryKeyword: "css box shadow generator",
    aliases: ["box-shadow css generator"],
    description: "Generate CSS box-shadow declarations with offset, blur, spread, color, opacity, and inset controls plus a live preview.",
    shortDescription: "Generate CSS box-shadow with live preview.",
    icon: "text",
    keywords: ["css box shadow generator","box shadow generator","css shadow maker"],
    popular: false,
    new: true,
    supportedFormats: ["CSS"],
    relatedToolIds: ["css-gradient-generator","css-border-radius-generator","color-palette-generator","css-clamp-generator"],
    seoTitle: "CSS Box Shadow Generator — Create box-shadow CSS | Tool Base",
    seoDescription: "Generate CSS box-shadow online with Tool Base. Adjust offsets, blur, spread, opacity, and inset, then copy the CSS.",
    h1: "CSS Box Shadow Generator",
    intro: "Tune a box shadow visually and copy the CSS. The CSS Box Shadow Generator updates a scoped preview as you adjust offsets, blur, spread, color, opacity, and inset.",
    convertHeading: "Generate CSS Box Shadow Online",
    howToHeading: "How the CSS Box Shadow Generator Works",
    featuresHeading: "Box Shadow Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Design Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["X/Y offset, blur, and spread","Color and opacity controls","Inset or outer shadow","Live preview","Copy CSS"],
    howToSteps: [
      { title: "Configure Shadow", description: "Set offsets, blur, spread, color, and opacity." },
      { title: "Generate CSS", description: "Create the box-shadow declaration." },
      { title: "Copy CSS", description: "Paste into your component styles." },
    ],
    faq: [
      { question: "Can I make an inset shadow?", answer: "Yes. Enable the inset option." },
      { question: "Is opacity supported?", answer: "Yes. Opacity is applied through rgba()." },
      { question: "Will generated CSS affect Tool Base?", answer: "No. Preview CSS is scoped to the preview element." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["CSS"],
    examples: [
      {
        title: "Soft drop shadow",
        description: "Static worked example — not your live result.",
        input: "0 8 24 0 #0f172a @ 0.25",
        output: "box-shadow: 0px 8px 24px 0px rgba(...);",
      },
    ],
  }),
  tool({
    id: "css-border-radius-generator",
    name: "CSS Border Radius Generator",
    slug: "css-border-radius-generator",
    category: "generators",
    exactPrimaryKeyword: "css border radius generator",
    aliases: ["border-radius css tool"],
    description: "Generate CSS border-radius values with linked or independent corner controls and a live preview.",
    shortDescription: "Generate CSS border-radius with linked corners.",
    icon: "text",
    keywords: ["css border radius generator","border radius generator","rounded corners css"],
    popular: false,
    new: true,
    supportedFormats: ["CSS"],
    relatedToolIds: ["css-box-shadow-generator","css-gradient-generator","color-palette-generator","css-clamp-generator"],
    seoTitle: "CSS Border Radius Generator — Rounded Corners CSS | Tool Base",
    seoDescription: "Generate CSS border-radius online with Tool Base. Link corners or set each independently, preview live, and copy CSS.",
    h1: "CSS Border Radius Generator",
    intro: "Shape rounded corners and copy the CSS. The CSS Border Radius Generator supports linked values or independent top-left, top-right, bottom-right, and bottom-left controls.",
    convertHeading: "Generate CSS Border Radius Online",
    howToHeading: "How the CSS Border Radius Generator Works",
    featuresHeading: "Border Radius Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Design Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Linked or unlinked corners","Live preview","Compact or four-value CSS","Mobile-friendly controls","Copy CSS"],
    howToSteps: [
      { title: "Set Corner Radii", description: "Link corners or edit each one." },
      { title: "Generate CSS", description: "Create the border-radius declaration." },
      { title: "Copy CSS", description: "Paste into your stylesheet." },
    ],
    faq: [
      { question: "Can corners be independent?", answer: "Yes. Unlink corners to edit each value." },
      { question: "Does it output shorthand?", answer: "Equal corners collapse to one value; otherwise four values are used." },
      { question: "Is there a preview?", answer: "Yes. A scoped preview reflects the generated radius." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["CSS"],
    examples: [
      {
        title: "Uniform radius",
        description: "Static worked example — not your live result.",
        input: "16px linked",
        output: "border-radius: 16px;",
      },
    ],
  }),
  tool({
    id: "css-clamp-generator",
    name: "CSS Clamp Generator",
    slug: "css-clamp-generator",
    category: "generators",
    exactPrimaryKeyword: "css clamp generator",
    aliases: ["css clamp() generator"],
    description: "Generate valid CSS clamp() expressions for responsive sizing with minimum, preferred, and maximum values.",
    shortDescription: "Generate responsive CSS clamp() expressions.",
    icon: "text",
    keywords: ["css clamp generator","clamp css generator","responsive font size clamp"],
    popular: false,
    new: true,
    supportedFormats: ["CSS"],
    relatedToolIds: ["css-gradient-generator","css-border-radius-generator","css-box-shadow-generator","color-palette-generator"],
    seoTitle: "CSS Clamp Generator — Responsive clamp() CSS | Tool Base",
    seoDescription: "Generate CSS clamp() expressions with Tool Base. Set min, preferred, and max values for responsive typography and spacing.",
    h1: "CSS Clamp Generator",
    intro: "Create responsive CSS with clamp(). The CSS Clamp Generator validates min/preferred/max relationships and outputs a property declaration you can copy.",
    convertHeading: "Generate CSS Clamp Online",
    howToHeading: "How the CSS Clamp Generator Works",
    featuresHeading: "Clamp Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Design Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Min / preferred / max controls","Common units","Invalid-range validation","Optional font-size preview","Copy CSS"],
    howToSteps: [
      { title: "Build a Clamp Expression", description: "Enter property, unit, and values." },
      { title: "Generate CSS", description: "Create a valid clamp() declaration." },
      { title: "Copy CSS", description: "Paste into your responsive styles." },
    ],
    faq: [
      { question: "What if min is greater than max?", answer: "The tool shows a validation error instead of invalid CSS." },
      { question: "Which dialect is this?", answer: "Standard CSS clamp(min, preferred, max)." },
      { question: "Can I use it for spacing?", answer: "Yes. Change the property name from font-size to width, padding, and more." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["CSS"],
    examples: [
      {
        title: "Responsive type",
        description: "Static worked example — not your live result.",
        input: "1rem, 2vw, 2rem",
        output: "font-size: clamp(1rem, 2vw, 2rem);",
      },
    ],
  }),
  tool({
    id: "html-boilerplate-generator",
    name: "HTML Boilerplate Generator",
    slug: "html-boilerplate-generator",
    category: "generators",
    exactPrimaryKeyword: "html boilerplate generator",
    aliases: ["html starter","html template generator"],
    description: "Generate a valid HTML5 boilerplate with language, charset, viewport, title, description, and optional CSS/JS/favicon references as copyable text.",
    shortDescription: "Generate a basic HTML5 document template.",
    icon: "text",
    keywords: ["html boilerplate generator","html5 boilerplate generator","html starter template"],
    popular: false,
    new: true,
    supportedFormats: ["HTML"],
    relatedToolIds: ["meta-tags-generator","open-graph-generator","robots-txt-generator","sitemap-xml-generator"],
    seoTitle: "HTML Boilerplate Generator — HTML5 Starter Template | Tool Base",
    seoDescription: "Generate an HTML5 boilerplate with Tool Base. Set title, language, meta description, and optional asset links, then copy or download.",
    h1: "HTML Boilerplate Generator",
    intro: "Create a clean HTML5 starter document. The HTML Boilerplate Generator outputs escaped template text — it does not execute scripts or inject markup into Tool Base.",
    convertHeading: "Generate an HTML Boilerplate",
    howToHeading: "How the HTML Boilerplate Generator Works",
    featuresHeading: "Boilerplate Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["HTML5 doctype and lang","Charset and viewport","Optional CSS, JS, favicon links","Copy HTML or download .html","Output treated as text only"],
    howToSteps: [
      { title: "Configure Document Options", description: "Set language, title, description, and asset paths." },
      { title: "Generate HTML", description: "Create the boilerplate text." },
      { title: "Copy or Download", description: "Use the HTML in your project files." },
    ],
    faq: [
      { question: "Is the HTML executed here?", answer: "No. It is displayed and downloaded as text only." },
      { question: "Can I include a stylesheet?", answer: "Yes. Provide an optional stylesheet path." },
      { question: "Is charset included?", answer: "Yes. UTF-8 is included by default." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["HTML"],
    examples: [
      {
        title: "Minimal document",
        description: "Static worked example — not your live result.",
        input: "title My Page",
        output: "<!DOCTYPE html>...",
      },
    ],
  }),
  tool({
    id: "meta-tags-generator",
    name: "Meta Tags Generator",
    slug: "meta-tags-generator",
    category: "generators",
    exactPrimaryKeyword: "meta tags generator",
    aliases: ["seo meta tags generator","metadata generator"],
    description: "Generate useful HTML head metadata including title, description, robots, viewport, canonical, and optional keywords/author fields.",
    shortDescription: "Generate HTML meta tags for pages.",
    icon: "text",
    keywords: ["meta tags generator","meta tag generator","html meta generator"],
    popular: false,
    new: true,
    supportedFormats: ["HTML meta tags"],
    relatedToolIds: ["open-graph-generator","html-boilerplate-generator","robots-txt-generator","sitemap-xml-generator"],
    seoTitle: "Meta Tags Generator — Create HTML Meta Tags | Tool Base",
    seoDescription: "Generate HTML meta tags with Tool Base. Build title, description, robots, viewport, and canonical tags you can copy into your head.",
    h1: "Meta Tags Generator",
    intro: "Assemble common HTML meta tags for a page. The Meta Tags Generator focuses on useful metadata and notes that meta keywords have limited modern ranking value.",
    convertHeading: "Generate HTML Meta Tags",
    howToHeading: "How the Meta Tags Generator Works",
    featuresHeading: "Meta Tag Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Title and description tags","Robots and viewport","Optional canonical URL","Optional keywords/author","Copy as HTML text"],
    howToSteps: [
      { title: "Enter Metadata", description: "Fill title, description, and related fields." },
      { title: "Generate Meta Tags", description: "Create the head markup text." },
      { title: "Copy Meta Tags", description: "Paste into your HTML head." },
    ],
    faq: [
      { question: "Do meta keywords still matter?", answer: "They have limited modern search-ranking value; focus on title and description." },
      { question: "Can I set robots directives?", answer: "Yes. Defaults to index, follow and is editable." },
      { question: "Is output executed?", answer: "No. Tags are shown as escaped text for copying." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["HTML meta tags"],
    examples: [
      {
        title: "Description tag",
        description: "Static worked example — not your live result.",
        input: "title + description",
        output: "<meta name=\"description\" content=\"...\" />",
      },
    ],
  }),
  tool({
    id: "open-graph-generator",
    name: "Open Graph Generator",
    slug: "open-graph-generator",
    category: "generators",
    exactPrimaryKeyword: "open graph generator",
    aliases: ["og:title generator","twitter card tags generator"],
    description: "Generate Open Graph meta tags for title, description, URL, image, site name, and type, with optional Twitter/X card tags.",
    shortDescription: "Generate Open Graph and optional Twitter card tags.",
    icon: "text",
    keywords: ["open graph generator","og tags generator","social meta tags generator"],
    popular: false,
    new: true,
    supportedFormats: ["HTML meta tags"],
    relatedToolIds: ["meta-tags-generator","html-boilerplate-generator","utm-url-builder","sitemap-xml-generator"],
    seoTitle: "Open Graph Generator — Create OG Meta Tags | Tool Base",
    seoDescription: "Generate Open Graph tags with Tool Base. Build og:title, description, url, image, and optional Twitter card tags.",
    h1: "Open Graph Generator",
    intro: "Prepare social sharing metadata with the Open Graph Generator. Validate http(s) URL fields where provided and optionally include Twitter/X card tags.",
    convertHeading: "Generate Open Graph Tags",
    howToHeading: "How the Open Graph Generator Works",
    featuresHeading: "Open Graph Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["og:title, description, url, image","Site name and type","Optional Twitter/X cards","URL validation","Copy tags as text"],
    howToSteps: [
      { title: "Enter Open Graph Fields", description: "Provide title, description, URL, and image." },
      { title: "Generate Tags", description: "Create OG markup instantly." },
      { title: "Copy Tags", description: "Paste into your page head." },
    ],
    faq: [
      { question: "Are Twitter tags included?", answer: "Optionally yes — enable Twitter/X card tags." },
      { question: "Do URLs get validated?", answer: "http(s) URL and image fields are validated when provided." },
      { question: "Does this preview social cards?", answer: "No. It generates tags only; platforms render their own previews." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["HTML meta tags"],
    examples: [
      {
        title: "Basic OG title",
        description: "Static worked example — not your live result.",
        input: "title Share Title",
        output: "<meta property=\"og:title\" content=\"Share Title\" />",
      },
    ],
  }),
  tool({
    id: "robots-txt-generator",
    name: "robots.txt Generator",
    slug: "robots-txt-generator",
    category: "generators",
    exactPrimaryKeyword: "robots txt generator",
    aliases: ["generate robots.txt","crawler rules generator"],
    description: "Generate robots.txt files with allow/disallow paths, user-agent, sitemap URL, and presets — including warnings for whole-site blocks.",
    shortDescription: "Generate robots.txt crawl rules and sitemap lines.",
    icon: "text",
    keywords: ["robots txt generator","robots.txt generator","robots txt maker"],
    popular: false,
    new: true,
    supportedFormats: ["robots.txt"],
    relatedToolIds: ["sitemap-xml-generator","meta-tags-generator","html-boilerplate-generator","open-graph-generator"],
    seoTitle: "robots.txt Generator — Create Crawl Rules | Tool Base",
    seoDescription: "Generate a robots.txt file with Tool Base. Choose presets, allow/disallow paths, and sitemap URL, then copy or download.",
    h1: "robots.txt Generator",
    intro: "Create a robots.txt for crawl directives. The robots.txt Generator includes helpful presets and warns when rules block the whole site so you do not publish restrictive files by accident.",
    convertHeading: "Generate a robots.txt File",
    howToHeading: "How the robots.txt Generator Works",
    featuresHeading: "robots.txt Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Allow all / block all / common / CMS presets","Custom allow and disallow paths","Sitemap URL support","Warning for whole-site blocks","Copy or download robots.txt"],
    howToSteps: [
      { title: "Choose Crawl Rules", description: "Pick a preset or enter custom paths." },
      { title: "Generate robots.txt", description: "Create the file text instantly." },
      { title: "Copy or Download", description: "Publish only after reviewing restrictive rules." },
    ],
    faq: [
      { question: "Can robots.txt block every search engine?", answer: "A Disallow: / rule can ask crawlers not to fetch pages, but compliance varies and authentication still matters for private content." },
      { question: "Does this submit rules to Google?", answer: "No. You host robots.txt on your site; search engines fetch it themselves." },
      { question: "Why the warning on block-all?", answer: "Blocking “/” is highly restrictive and easy to mispublish." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["robots.txt"],
    examples: [
      {
        title: "Common website",
        description: "Static worked example — not your live result.",
        input: "allow / + disallow /admin/",
        output: "User-agent: *\\nAllow: /\\nDisallow: /admin/",
      },
    ],
  }),
  tool({
    id: "sitemap-xml-generator",
    name: "Sitemap XML Generator",
    slug: "sitemap-xml-generator",
    category: "generators",
    exactPrimaryKeyword: "sitemap generator",
    aliases: ["generate sitemap xml","url sitemap builder"],
    description: "Generate a valid XML sitemap from a list of URLs with optional lastmod, changefreq, and priority fields and safe XML escaping.",
    shortDescription: "Generate an XML sitemap from a URL list.",
    icon: "text",
    keywords: ["sitemap generator","xml sitemap generator","sitemap.xml generator"],
    popular: false,
    new: true,
    supportedFormats: ["XML"],
    relatedToolIds: ["robots-txt-generator","utm-url-builder","meta-tags-generator","url-slug-generator"],
    seoTitle: "Sitemap XML Generator — Create sitemap.xml | Tool Base",
    seoDescription: "Generate an XML sitemap with Tool Base. Paste URLs, add optional lastmod/changefreq/priority, then copy or download sitemap.xml.",
    h1: "Sitemap XML Generator",
    intro: "Turn a URL list into sitemap.xml. The Sitemap XML Generator validates URLs, escapes XML safely, and reminds you that creating a sitemap does not automatically submit it to Google.",
    convertHeading: "Generate a Sitemap XML File",
    howToHeading: "How the Sitemap XML Generator Works",
    featuresHeading: "Sitemap Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Multi-URL input","Optional lastmod, changefreq, priority","XML escaping","URL validation","Copy or download sitemap.xml"],
    howToSteps: [
      { title: "Enter URLs", description: "Paste one URL per line." },
      { title: "Generate Sitemap", description: "Create valid XML instantly." },
      { title: "Copy or Download", description: "Host the file on your site as needed." },
    ],
    faq: [
      { question: "Does creating a sitemap automatically submit it to Google?", answer: "No. Submission is a separate step in Search Console or via other tools." },
      { question: "Are URLs validated?", answer: "Yes. Each loc must be a valid http(s) URL." },
      { question: "Is XML escaped?", answer: "Yes. Special characters are escaped for valid XML." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["XML"],
    examples: [
      {
        title: "Two URLs",
        description: "Static worked example — not your live result.",
        input: "https://example.com/\\nhttps://example.com/about",
        output: "<urlset>...</urlset>",
      },
    ],
  }),
  tool({
    id: "gitignore-generator",
    name: ".gitignore Generator",
    slug: "gitignore-generator",
    category: "generators",
    exactPrimaryKeyword: "gitignore generator",
    aliases: ["generate gitignore","gitignore maker"],
    description: "Generate a .gitignore file by combining curated local templates for Node.js, React, Next.js, Python, and more — no remote fetch required.",
    shortDescription: "Generate a .gitignore from local project templates.",
    icon: "text",
    keywords: ["gitignore generator",".gitignore generator","gitignore template generator"],
    popular: false,
    new: true,
    supportedFormats: [".gitignore"],
    relatedToolIds: ["json-mock-data-generator","html-boilerplate-generator","random-string-generator","uuid-generator"],
    seoTitle: ".gitignore Generator — Project Ignore Templates | Tool Base",
    seoDescription: "Generate a .gitignore with Tool Base. Combine Node, React, Next.js, Python, and OS templates, then copy or download.",
    h1: ".gitignore Generator",
    intro: "Assemble a practical .gitignore from curated local templates. The .gitignore Generator supports multiple selections such as Node.js, Next.js, Python, and OS ignores without fetching remote template packs.",
    convertHeading: "Generate a .gitignore File",
    howToHeading: "How the .gitignore Generator Works",
    featuresHeading: ".gitignore Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Multi-template selection","Node, React, Next.js, Python, and more","macOS and Windows ignores","Copy or download .gitignore","Local templates only"],
    howToSteps: [
      { title: "Select Templates", description: "Choose one or more project stacks." },
      { title: "Generate .gitignore", description: "Combine curated ignore rules." },
      { title: "Copy or Download", description: "Add the file to your repository root." },
    ],
    faq: [
      { question: "Are templates fetched from the internet?", answer: "No. Templates are curated locally in Tool Base." },
      { question: "Can I combine stacks?", answer: "Yes. Select multiple templates at once." },
      { question: "Is this a complete security policy?", answer: "No. It is a convenience ignore list starter." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: [".gitignore"],
    examples: [
      {
        title: "Node + macOS",
        description: "Static worked example — not your live result.",
        input: "node, macos",
        output: "node_modules/\\n.DS_Store",
      },
    ],
  }),
  tool({
    id: "json-mock-data-generator",
    name: "JSON Mock Data Generator",
    slug: "json-mock-data-generator",
    category: "generators",
    exactPrimaryKeyword: "json mock data generator",
    aliases: ["generate mock json","test json generator"],
    description: "Generate synthetic JSON test data from field definitions such as name, email, age, boolean, and UUID — clearly fictional values with quantity limits.",
    shortDescription: "Generate synthetic JSON mock records.",
    icon: "text",
    keywords: ["json mock data generator","mock json generator","fake json data generator"],
    popular: false,
    new: true,
    supportedFormats: ["JSON"],
    relatedToolIds: ["json-formatter","json-validator","json-to-csv","csv-test-data-generator"],
    seoTitle: "JSON Mock Data Generator — Synthetic Test JSON | Tool Base",
    seoDescription: "Generate synthetic JSON mock data with Tool Base. Define fields and record counts, then copy or download valid JSON.",
    h1: "JSON Mock Data Generator",
    intro: "Create synthetic JSON for fixtures and demos. The JSON Mock Data Generator uses fictional values only and enforces record limits so large requests do not freeze the browser.",
    convertHeading: "Generate JSON Mock Data",
    howToHeading: "How the JSON Mock Data Generator Works",
    featuresHeading: "Mock Data Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Field name and type editor","UUID, email, boolean, and more","Record count limits","Valid JSON output","Copy or download JSON"],
    howToSteps: [
      { title: "Define Fields", description: "Add field names and types." },
      { title: "Generate JSON", description: "Create synthetic records instantly." },
      { title: "Copy or Download", description: "Use the JSON in tests or fixtures." },
    ],
    faq: [
      { question: "Is this real personal data?", answer: "No. Values are synthetic test data." },
      { question: "Is there a max record count?", answer: "Yes. Large requests are capped for browser performance." },
      { question: "Can I download the result?", answer: "Yes. Download as mock-data.json." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["JSON"],
    examples: [
      {
        title: "Two people",
        description: "Static worked example — not your live result.",
        input: "name + email, count 2",
        output: "[{ \"name\": \"...\", \"email\": \"user...@example.com\" }]",
      },
    ],
  }),
  tool({
    id: "csv-test-data-generator",
    name: "CSV Test Data Generator",
    slug: "csv-test-data-generator",
    category: "generators",
    exactPrimaryKeyword: "csv test data generator",
    aliases: ["generate csv test data","mock csv generator"],
    description: "Generate synthetic CSV test data with configurable columns, row counts, delimiters, and proper CSV quoting.",
    shortDescription: "Generate synthetic CSV test rows.",
    icon: "text",
    keywords: ["csv test data generator","csv generator","fake csv data generator"],
    popular: false,
    new: true,
    supportedFormats: ["CSV"],
    relatedToolIds: ["json-mock-data-generator","json-to-csv","csv-to-json","json-formatter"],
    seoTitle: "CSV Test Data Generator — Synthetic CSV Rows | Tool Base",
    seoDescription: "Generate synthetic CSV test data with Tool Base. Configure columns, rows, and delimiter, then copy or download CSV.",
    h1: "CSV Test Data Generator",
    intro: "Produce CSV fixtures for imports and demos. The CSV Test Data Generator creates fictional rows, supports common delimiters, and quotes fields safely.",
    convertHeading: "Generate CSV Test Data",
    howToHeading: "How the CSV Test Data Generator Works",
    featuresHeading: "CSV Generator Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Configurable columns and types","Row count limits","Comma, semicolon, or tab delimiter","Proper CSV quoting","Copy or download CSV"],
    howToSteps: [
      { title: "Define Columns", description: "Set column names and types." },
      { title: "Generate CSV", description: "Create synthetic rows instantly." },
      { title: "Copy or Download", description: "Use the CSV in your test workflow." },
    ],
    faq: [
      { question: "Are emails real?", answer: "No. Emails use the example.com test domain." },
      { question: "How are quotes handled?", answer: "Fields with commas or quotes are escaped per CSV rules." },
      { question: "Is there a row limit?", answer: "Yes, to keep generation responsive." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["CSV"],
    examples: [
      {
        title: "Name and email",
        description: "Static worked example — not your live result.",
        input: "2 rows",
        output: "Name,Email\\nAva Rivera,user1...@example.com",
      },
    ],
  }),
  tool({
    id: "cron-expression-generator",
    name: "Cron Expression Generator",
    slug: "cron-expression-generator",
    category: "generators",
    exactPrimaryKeyword: "cron expression generator",
    aliases: ["cron schedule generator","crontab expression builder"],
    description: "Generate 5-field UNIX cron expressions from presets or custom fields and show a human-readable interpretation. Dialects vary by system.",
    shortDescription: "Generate UNIX cron expressions with explanations.",
    icon: "text",
    keywords: ["cron expression generator","cron generator","crontab generator"],
    popular: false,
    new: true,
    supportedFormats: ["Cron expression"],
    relatedToolIds: ["json-mock-data-generator","uuid-generator","random-number-generator","utm-url-builder"],
    seoTitle: "Cron Expression Generator — Build Crontab Schedules | Tool Base",
    seoDescription: "Generate cron expressions with Tool Base. Use presets or custom fields, copy the expression, and read a plain-language summary.",
    h1: "Cron Expression Generator",
    intro: "Build a schedule expression with the Cron Expression Generator. It targets a 5-field UNIX crontab dialect and clearly states that not every scheduler uses identical syntax.",
    convertHeading: "Generate a Cron Expression",
    howToHeading: "How the Cron Expression Generator Works",
    featuresHeading: "Cron Features",
    supportedFormatsHeading: "Output Details",
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: ["Common presets","Custom 5-field editing","Human-readable summary","Dialect labeling","Copy expression"],
    howToSteps: [
      { title: "Choose a Schedule", description: "Pick a preset or edit minute/hour/day fields." },
      { title: "Generate Expression", description: "Create the cron string and summary." },
      { title: "Copy Expression", description: "Paste into your scheduler configuration." },
    ],
    faq: [
      { question: "Are all cron syntaxes identical?", answer: "No. This tool uses a 5-field UNIX crontab dialect; some systems add seconds or differ on day-of-week numbering." },
      { question: "Does Tool Base run the cron job?", answer: "No. It only generates and explains expressions." },
      { question: "What does 0 9 * * 1-5 mean?", answer: "It commonly means 09:00 Monday through Friday in UNIX crontab." },
    ],
    inputFormats: ["Options / text inputs"],
    outputFormats: ["Cron expression"],
    examples: [
      {
        title: "Weekdays at 9",
        description: "Static worked example — not your live result.",
        input: "every-weekday preset",
        output: "0 9 * * 1-5",
      },
    ],
  }),
];
