import type { ToolDefinition } from "./types";

function tool(
  partial: Omit<ToolDefinition, "route" | "status"> & {
    status?: ToolDefinition["status"];
  },
): ToolDefinition {
  return {
    ...partial,
    route: `/tools/${partial.slug}`,
    status: partial.status ?? "available",
  };
}

/** Developer / coding tools — Prompt 9 */
export const developerTools: ToolDefinition[] = [
  tool({
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    category: "developer-tools",
    description: "Format and beautify JSON with readable indentation for objects, arrays, and nested structures.",
    shortDescription: "Format and beautify JSON.",
    icon: "code",
    keywords: [
      "json formatter",
      "format json",
      "json beautifier",
      "pretty print json",
    ],
    popular: true,
    new: false,
    supportedFormats: ["JSON"],
    relatedToolIds: [
      "json-validator",
      "json-minifier",
      "xml-formatter",
      "yaml-to-json",
      "json-to-yaml",
    ],
    seoTitle: "JSON Formatter — Format JSON Online | ToolMyra",
    seoDescription: "Format and beautify JSON online with ToolMyra. Paste your JSON, validate its syntax, format nested structures, and copy or download the result.",
    h1: "JSON Formatter",
    intro: "Paste raw JSON and format it into a clean, readable structure. Invalid JSON is reported instead of silently reformatted.",
    convertHeading: "Format JSON Online",
    howToHeading: "How to Format JSON",
    featuresHeading: "JSON Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Readable indentation options",
      "Nested object and array support",
      "Clear invalid-JSON errors",
      "Copy and download JSON",
      "Works with Unicode text",
    ],
    howToSteps: [
      {
        title: "Paste Your JSON",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your JSON",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does formatting change my data?",
        answer: "No. Only whitespace and indentation change when the JSON is valid.",
      },
      {
        question: "What happens with invalid JSON?",
        answer: "Formatting stops and a clear error is shown.",
      },
      {
        question: "Can I choose indentation?",
        answer: "Yes. Choose 2 spaces, 4 spaces, or tabs.",
      },
      {
        question: "Is my JSON uploaded?",
        answer: "No. Formatting runs in your browser session.",
      },
    ],
    inputFormats: ["JSON"],
    outputFormats: ["JSON"],
  }),
  tool({
    id: "json-validator",
    name: "JSON Validator",
    slug: "json-validator",
    category: "developer-tools",
    description: "Validate JSON syntax and get helpful error location details when parsing fails.",
    shortDescription: "Validate JSON syntax online.",
    icon: "code",
    keywords: [
      "json validator",
      "validate json",
      "json checker",
      "json syntax checker",
    ],
    popular: true,
    new: false,
    supportedFormats: ["JSON"],
    relatedToolIds: [
      "json-formatter",
      "json-minifier",
      "xml-validator",
      "json-to-csv",
      "json-to-xml",
    ],
    seoTitle: "JSON Validator — Validate JSON Online | ToolMyra",
    seoDescription: "Validate JSON online with ToolMyra. Check JSON syntax instantly and review helpful error details when parsing fails.",
    h1: "JSON Validator",
    intro: "Check whether your JSON is valid. When parsing fails, see a clear message with approximate location details where available.",
    convertHeading: "Validate JSON Online",
    howToHeading: "How to Validate JSON",
    featuresHeading: "JSON Validator Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Real parser-based validation",
      "Valid / invalid status",
      "Line and position hints when available",
      "Live validation as you type",
      "No account required",
    ],
    howToSteps: [
      {
        title: "Paste Your JSON",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Review Validation",
        description: "Run the action or review the live result.",
      },
      {
        title: "Fix Issues and Recheck",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Is validation live?",
        answer: "Yes. Results update as you edit.",
      },
      {
        question: "Does it repair JSON?",
        answer: "No. It validates and explains errors.",
      },
      {
        question: "Are empty inputs valid?",
        answer: "Empty input is treated as incomplete, not valid JSON.",
      },
      {
        question: "Private?",
        answer: "Yes. Validation stays in your browser.",
      },
    ],
    inputFormats: ["JSON"],
    outputFormats: ["JSON"],
  }),
  tool({
    id: "json-minifier",
    name: "JSON Minifier",
    slug: "json-minifier",
    category: "developer-tools",
    description: "Minify valid JSON by removing unnecessary whitespace without changing values.",
    shortDescription: "Minify JSON by removing whitespace.",
    icon: "code",
    keywords: [
      "json minifier",
      "minify json",
      "compress json",
      "json compress",
    ],
    popular: false,
    new: false,
    supportedFormats: ["JSON"],
    relatedToolIds: [
      "json-formatter",
      "json-validator",
      "javascript-minifier",
      "css-minifier",
      "html-minifier",
    ],
    seoTitle: "JSON Minifier — Minify JSON Online | ToolMyra",
    seoDescription: "Minify JSON online with ToolMyra. Remove unnecessary whitespace from valid JSON and copy or download the compact result.",
    h1: "JSON Minifier",
    intro: "Compress valid JSON into a compact single-line form. Values stay the same — only unnecessary whitespace is removed.",
    convertHeading: "Minify JSON Online",
    howToHeading: "How to Minify JSON",
    featuresHeading: "JSON Minifier Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Validates before minifying",
      "Preserves values exactly",
      "Compact output",
      "Copy and download",
      "Clear parse errors",
    ],
    howToSteps: [
      {
        title: "Paste Your JSON",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Minify Your JSON",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does minifying change values?",
        answer: "No. Only whitespace is removed.",
      },
      {
        question: "What if JSON is invalid?",
        answer: "Minifying stops and an error is shown.",
      },
      {
        question: "Can I format it again later?",
        answer: "Yes. Use the JSON Formatter.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["JSON"],
    outputFormats: ["JSON"],
  }),
  tool({
    id: "html-formatter",
    name: "HTML Formatter",
    slug: "html-formatter",
    category: "developer-tools",
    description: "Format HTML source into readable indentation without executing markup.",
    shortDescription: "Format HTML with readable indentation.",
    icon: "code",
    keywords: [
      "html formatter",
      "beautify html",
      "format html",
      "pretty print html",
    ],
    popular: true,
    new: false,
    supportedFormats: ["HTML"],
    relatedToolIds: [
      "html-minifier",
      "css-formatter",
      "html-entity-encoder",
      "markdown-to-html",
      "html-to-markdown",
    ],
    seoTitle: "HTML Formatter — Format HTML Online | ToolMyra",
    seoDescription: "Format and beautify HTML online with ToolMyra. Indent nested elements and copy or download readable HTML source.",
    h1: "HTML Formatter",
    intro: "Turn messy HTML into readable source with consistent indentation. Markup is treated as text and is never executed.",
    convertHeading: "Format HTML Online",
    howToHeading: "How to Format HTML",
    featuresHeading: "HTML Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Readable indentation",
      "Nested element support",
      "Source-only display",
      "Copy and download HTML",
      "No script execution",
    ],
    howToSteps: [
      {
        title: "Paste Your HTML",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your HTML",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Is HTML executed?",
        answer: "No. It is formatted as source text only.",
      },
      {
        question: "Are attributes preserved?",
        answer: "Yes. Formatting focuses on structure and whitespace.",
      },
      {
        question: "Can I minify afterward?",
        answer: "Yes. Use the HTML Minifier.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["HTML"],
    outputFormats: ["HTML"],
  }),
  tool({
    id: "html-minifier",
    name: "HTML Minifier",
    slug: "html-minifier",
    category: "developer-tools",
    description: "Minify HTML by reducing unnecessary whitespace while keeping markup conservative and safe.",
    shortDescription: "Minify HTML safely.",
    icon: "code",
    keywords: [
      "html minifier",
      "minify html",
      "compress html",
    ],
    popular: false,
    new: false,
    supportedFormats: ["HTML"],
    relatedToolIds: [
      "html-formatter",
      "css-minifier",
      "javascript-minifier",
      "html-entity-encoder",
      "html-to-markdown",
    ],
    seoTitle: "HTML Minifier — Minify HTML Online | ToolMyra",
    seoDescription: "Minify HTML online with ToolMyra. Reduce unnecessary whitespace conservatively and copy the compact HTML source.",
    h1: "HTML Minifier",
    intro: "Reduce unnecessary whitespace in HTML source without executing scripts or breaking quoted attributes.",
    convertHeading: "Minify HTML Online",
    howToHeading: "How to Minify HTML",
    featuresHeading: "HTML Minifier Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Conservative whitespace reduction",
      "Source-only processing",
      "No script execution",
      "Copy and download",
      "Clear error handling",
    ],
    howToSteps: [
      {
        title: "Paste Your HTML",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Minify Your HTML",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Will scripts run?",
        answer: "No. HTML is never executed.",
      },
      {
        question: "Is minification aggressive?",
        answer: "It is intentionally conservative to avoid breaking markup.",
      },
      {
        question: "Can I format again?",
        answer: "Yes. Use the HTML Formatter.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["HTML"],
    outputFormats: ["HTML"],
  }),
  tool({
    id: "css-formatter",
    name: "CSS Formatter",
    slug: "css-formatter",
    category: "developer-tools",
    description: "Format CSS selectors, declarations, and at-rules into readable source.",
    shortDescription: "Format CSS for readability.",
    icon: "code",
    keywords: [
      "css formatter",
      "format css",
      "beautify css",
      "pretty print css",
    ],
    popular: false,
    new: false,
    supportedFormats: ["CSS"],
    relatedToolIds: [
      "css-minifier",
      "html-formatter",
      "javascript-formatter",
      "html-minifier",
      "json-formatter",
    ],
    seoTitle: "CSS Formatter — Format CSS Online | ToolMyra",
    seoDescription: "Format CSS online with ToolMyra. Beautify selectors and declarations, then copy or download readable CSS.",
    h1: "CSS Formatter",
    intro: "Beautify CSS source for easier reading and review. Formatting preserves CSS semantics while improving indentation.",
    convertHeading: "Format CSS Online",
    howToHeading: "How to Format CSS",
    featuresHeading: "CSS Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Readable selector formatting",
      "At-rule support",
      "Indentation options",
      "Copy and download CSS",
      "Clear parse errors",
    ],
    howToSteps: [
      {
        title: "Paste Your CSS",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your CSS",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does formatting change CSS meaning?",
        answer: "It should not. Formatting focuses on whitespace and structure.",
      },
      {
        question: "Can I minify afterward?",
        answer: "Yes. Use the CSS Minifier.",
      },
      {
        question: "Are comments kept?",
        answer: "Formatting preserves comments where the formatter allows.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["CSS"],
    outputFormats: ["CSS"],
  }),
  tool({
    id: "css-minifier",
    name: "CSS Minifier",
    slug: "css-minifier",
    category: "developer-tools",
    description: "Minify CSS by removing safe unnecessary whitespace and comments while preserving behavior.",
    shortDescription: "Minify CSS without changing meaning.",
    icon: "code",
    keywords: [
      "css minifier",
      "minify css",
      "compress css",
    ],
    popular: false,
    new: false,
    supportedFormats: ["CSS"],
    relatedToolIds: [
      "css-formatter",
      "html-minifier",
      "javascript-minifier",
      "html-formatter",
      "json-minifier",
    ],
    seoTitle: "CSS Minifier — Minify CSS Online | ToolMyra",
    seoDescription: "Minify CSS online with ToolMyra. Remove safe unnecessary whitespace and copy compact CSS for production use.",
    h1: "CSS Minifier",
    intro: "Create compact CSS by removing safe unnecessary whitespace and comments. Strings, URLs, and custom properties are handled carefully.",
    convertHeading: "Minify CSS Online",
    howToHeading: "How to Minify CSS",
    featuresHeading: "CSS Minifier Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Safe whitespace reduction",
      "Careful string handling",
      "Copy and download",
      "Clear minify errors",
      "No CSS execution",
    ],
    howToSteps: [
      {
        title: "Paste Your CSS",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Minify Your CSS",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Can minifying break calc()?",
        answer: "The minifier is configured conservatively to avoid unsafe transforms.",
      },
      {
        question: "Are comments removed?",
        answer: "Yes, standard comments are removed during minify.",
      },
      {
        question: "Can I format again?",
        answer: "Yes. Use the CSS Formatter.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["CSS"],
    outputFormats: ["CSS"],
  }),
  tool({
    id: "javascript-formatter",
    name: "JavaScript Formatter",
    slug: "javascript-formatter",
    category: "developer-tools",
    description: "Format modern JavaScript source for readability without executing any code.",
    shortDescription: "Format JavaScript source safely.",
    icon: "code",
    keywords: [
      "javascript formatter",
      "format javascript",
      "js beautifier",
      "prettier javascript",
    ],
    popular: true,
    new: false,
    supportedFormats: ["JavaScript"],
    relatedToolIds: [
      "javascript-minifier",
      "json-formatter",
      "css-formatter",
      "html-formatter",
      "regex-tester",
    ],
    seoTitle: "JavaScript Formatter — Format JS Online | ToolMyra",
    seoDescription: "Format JavaScript online with ToolMyra. Beautify source code safely without executing it, then copy or download the result.",
    h1: "JavaScript Formatter",
    intro: "Beautify JavaScript source with a reliable formatter. Your code is treated as text and is never executed in the browser.",
    convertHeading: "Format JavaScript Online",
    howToHeading: "How to Format JavaScript",
    featuresHeading: "JavaScript Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Modern syntax support where available",
      "Source-only formatting",
      "No code execution",
      "Copy and download JS",
      "Helpful parse errors",
    ],
    howToSteps: [
      {
        title: "Paste Your JavaScript",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your JavaScript",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Is my JavaScript executed?",
        answer: "Never. This tool only formats source text.",
      },
      {
        question: "What if parsing fails?",
        answer: "A clear error is shown and no formatted output is claimed.",
      },
      {
        question: "Can I minify afterward?",
        answer: "Yes. Use the JavaScript Minifier.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["JavaScript"],
    outputFormats: ["JavaScript"],
  }),
  tool({
    id: "javascript-minifier",
    name: "JavaScript Minifier",
    slug: "javascript-minifier",
    category: "developer-tools",
    description: "Minify JavaScript with a proper parser-based minifier without executing code.",
    shortDescription: "Minify JavaScript source safely.",
    icon: "code",
    keywords: [
      "javascript minifier",
      "minify javascript",
      "js minify",
      "uglify javascript",
    ],
    popular: false,
    new: false,
    supportedFormats: ["JavaScript"],
    relatedToolIds: [
      "javascript-formatter",
      "css-minifier",
      "html-minifier",
      "json-minifier",
      "regex-tester",
    ],
    seoTitle: "JavaScript Minifier — Minify JS Online | ToolMyra",
    seoDescription: "Minify JavaScript online with ToolMyra. Compress source safely without executing code, then copy or download the result.",
    h1: "JavaScript Minifier",
    intro: "Compress JavaScript source with a parser-based minifier. Code is never evaluated or run in ToolMyra.",
    convertHeading: "Minify JavaScript Online",
    howToHeading: "How to Minify JavaScript",
    featuresHeading: "JavaScript Minifier Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Parser-based minification",
      "No code execution",
      "Clear parse errors",
      "Copy and download",
      "Source-only workflow",
    ],
    howToSteps: [
      {
        title: "Paste Your JavaScript",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Minify Your JavaScript",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does this run my code?",
        answer: "No. Minification transforms source text only.",
      },
      {
        question: "What if syntax is invalid?",
        answer: "Minifying stops with a helpful error.",
      },
      {
        question: "Is mangling used?",
        answer: "Yes, for compact output while preserving valid program behavior as the minifier guarantees.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["JavaScript"],
    outputFormats: ["JavaScript"],
  }),
  tool({
    id: "xml-formatter",
    name: "XML Formatter",
    slug: "xml-formatter",
    category: "developer-tools",
    description: "Parse and format XML into readable indentation with safe processing settings.",
    shortDescription: "Format XML with indentation.",
    icon: "code",
    keywords: [
      "xml formatter",
      "format xml",
      "beautify xml",
      "pretty print xml",
    ],
    popular: false,
    new: false,
    supportedFormats: ["XML"],
    relatedToolIds: [
      "xml-validator",
      "json-formatter",
      "json-to-xml",
      "xml-to-json",
      "html-formatter",
    ],
    seoTitle: "XML Formatter — Format XML Online | ToolMyra",
    seoDescription: "Format XML online with ToolMyra. Beautify valid XML with readable indentation and copy or download the result.",
    h1: "XML Formatter",
    intro: "Format valid XML into a readable tree. Malformed XML produces an error instead of fake formatted output.",
    convertHeading: "Format XML Online",
    howToHeading: "How to Format XML",
    featuresHeading: "XML Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Real XML parsing",
      "Readable indentation",
      "Safe processing settings",
      "Clear malformed-XML errors",
      "Copy and download",
    ],
    howToSteps: [
      {
        title: "Paste Your XML",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your XML",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does this fetch external entities?",
        answer: "No. Processing is configured to avoid unsafe external behavior.",
      },
      {
        question: "What if XML is invalid?",
        answer: "Formatting stops and an error is shown.",
      },
      {
        question: "Is XML executed?",
        answer: "No. It is treated as data.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["XML"],
    outputFormats: ["XML"],
  }),
  tool({
    id: "xml-validator",
    name: "XML Validator",
    slug: "xml-validator",
    category: "developer-tools",
    description: "Validate XML syntax and review parser errors with line and column details when available.",
    shortDescription: "Validate XML syntax online.",
    icon: "code",
    keywords: [
      "xml validator",
      "validate xml",
      "xml checker",
    ],
    popular: false,
    new: false,
    supportedFormats: ["XML"],
    relatedToolIds: [
      "xml-formatter",
      "json-validator",
      "xml-to-json",
      "json-to-xml",
      "html-formatter",
    ],
    seoTitle: "XML Validator — Validate XML Online | ToolMyra",
    seoDescription: "Validate XML online with ToolMyra. Check XML syntax and review parser errors with helpful location details.",
    h1: "XML Validator",
    intro: "Confirm whether your XML is well-formed. Invalid documents show a clear parser message with location details when available.",
    convertHeading: "Validate XML Online",
    howToHeading: "How to Validate XML",
    featuresHeading: "XML Validator Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Real XML validation",
      "Valid / invalid status",
      "Line and column hints",
      "Live validation",
      "Safe parsing",
    ],
    howToSteps: [
      {
        title: "Paste Your XML",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Review Validation",
        description: "Run the action or review the live result.",
      },
      {
        title: "Fix Issues and Recheck",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Is validation live?",
        answer: "Yes.",
      },
      {
        question: "Are external resources loaded?",
        answer: "No.",
      },
      {
        question: "Does valid mean schema-valid?",
        answer: "This checks well-formed XML syntax, not an external schema.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["XML"],
    outputFormats: ["XML"],
  }),
  tool({
    id: "sql-formatter",
    name: "SQL Formatter",
    slug: "sql-formatter",
    category: "developer-tools",
    description: "Format SQL SELECT, INSERT, UPDATE, DELETE, and common clauses into readable text without executing anything.",
    shortDescription: "Format SQL queries for readability.",
    icon: "code",
    keywords: [
      "sql formatter",
      "format sql",
      "beautify sql",
      "pretty print sql",
    ],
    popular: true,
    new: false,
    supportedFormats: ["SQL"],
    relatedToolIds: [
      "sql-minifier",
      "json-formatter",
      "regex-tester",
      "text-diff-checker",
      "find-and-replace",
    ],
    seoTitle: "SQL Formatter — Format SQL Online | ToolMyra",
    seoDescription: "Format SQL online with ToolMyra. Beautify queries for readability without executing them against any database.",
    h1: "SQL Formatter",
    intro: "Beautify SQL text for easier review. Nothing is executed against a database — this tool only transforms and displays SQL.",
    convertHeading: "Format SQL Online",
    howToHeading: "How to Format SQL",
    featuresHeading: "SQL Formatter Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Readable keyword formatting",
      "Common SQL clause support",
      "No database execution",
      "Copy and download SQL",
      "Clear formatter errors",
    ],
    howToSteps: [
      {
        title: "Paste Your SQL",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Format Your SQL",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Does this run SQL?",
        answer: "Never. There is no database connection.",
      },
      {
        question: "Which SQL dialects work?",
        answer: "Common SQL syntax is supported where the formatter allows.",
      },
      {
        question: "Can I minify afterward?",
        answer: "Yes. Use the SQL Minifier.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["SQL"],
    outputFormats: ["SQL"],
  }),
  tool({
    id: "sql-minifier",
    name: "SQL Minifier",
    slug: "sql-minifier",
    category: "developer-tools",
    description: "Minify SQL by removing safe unnecessary whitespace while preserving string literals and identifiers.",
    shortDescription: "Minify SQL text safely.",
    icon: "code",
    keywords: [
      "sql minifier",
      "minify sql",
      "compress sql",
    ],
    popular: false,
    new: false,
    supportedFormats: ["SQL"],
    relatedToolIds: [
      "sql-formatter",
      "json-minifier",
      "javascript-minifier",
      "find-and-replace",
      "text-cleaner",
    ],
    seoTitle: "SQL Minifier — Minify SQL Online | ToolMyra",
    seoDescription: "Minify SQL online with ToolMyra. Collapse safe whitespace without executing queries or corrupting string literals.",
    h1: "SQL Minifier",
    intro: "Create compact SQL text by removing safe unnecessary whitespace. String literals and comments are handled carefully, and nothing is executed.",
    convertHeading: "Minify SQL Online",
    howToHeading: "How to Minify SQL",
    featuresHeading: "SQL Minifier Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Whitespace collapsing",
      "Literal-aware handling",
      "No SQL execution",
      "Copy and download",
      "Clear errors for empty input",
    ],
    howToSteps: [
      {
        title: "Paste Your SQL",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Minify Your SQL",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Can this corrupt strings?",
        answer: "Minifying preserves quoted strings and identifiers.",
      },
      {
        question: "Does it execute queries?",
        answer: "No.",
      },
      {
        question: "Are comments removed?",
        answer: "Line and block comments are stripped during minify.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["SQL"],
    outputFormats: ["SQL"],
  }),
  tool({
    id: "regex-tester",
    name: "Regex Tester",
    slug: "regex-tester",
    category: "developer-tools",
    description: "Test regular expressions against sample text with match details, groups, and timeout protection.",
    shortDescription: "Test regular expressions safely.",
    icon: "code",
    keywords: [
      "regex tester",
      "regular expression tester",
      "regex checker",
      "test regex",
    ],
    popular: true,
    new: true,
    supportedFormats: ["Regex"],
    relatedToolIds: [
      "regex-generator",
      "text-diff-checker",
      "find-and-replace",
      "javascript-formatter",
      "word-counter",
    ],
    seoTitle: "Regex Tester — Test Regular Expressions Online | ToolMyra",
    seoDescription: "Test regular expressions against sample text with ToolMyra. Review matches, capture groups, and regex errors in a simple online tester.",
    h1: "Regex Tester",
    intro: "Enter a pattern and test text to review matches and capture groups. Expensive patterns are stopped automatically so they cannot freeze the page.",
    convertHeading: "Test Regular Expressions Online",
    howToHeading: "How to Use the Regex Tester",
    featuresHeading: "Regex Tester Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Match count and details",
      "Capture groups",
      "Highlighting without HTML injection",
      "Timeout protection",
      "Clear invalid-pattern errors",
    ],
    howToSteps: [
      {
        title: "Enter Your Pattern",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Enter Test Text",
        description: "Run the action or review the live result.",
      },
      {
        title: "Review Matches",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Can a bad regex freeze the page?",
        answer: "Expensive evaluations are stopped after a short safety threshold.",
      },
      {
        question: "Are matches highlighted safely?",
        answer: "Yes. Your text is treated as data, not HTML.",
      },
      {
        question: "Which flags are supported?",
        answer: "Common flags such as g, i, m, s, u, and y.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Regex"],
    outputFormats: ["Regex"],
  }),
  tool({
    id: "regex-generator",
    name: "Regex Generator",
    slug: "regex-generator",
    category: "developer-tools",
    description: "Generate practical regular expressions from structured templates and options, then test them in the Regex Tester.",
    shortDescription: "Generate regex from templates.",
    icon: "code",
    keywords: [
      "regex generator",
      "generate regex",
      "regular expression builder",
    ],
    popular: false,
    new: true,
    supportedFormats: ["Regex"],
    relatedToolIds: [
      "regex-tester",
      "find-and-replace",
      "text-cleaner",
      "url-encoder",
      "html-entity-encoder",
    ],
    seoTitle: "Regex Generator — Build Regex Patterns Online | ToolMyra",
    seoDescription: "Generate practical regex patterns online with ToolMyra. Choose templates and options, then copy or test the expression.",
    h1: "Regex Generator",
    intro: "Build a starting regex from templates like email-like, URL-like, digits, and custom character sets. Generated patterns are practical templates, not universal validators.",
    convertHeading: "Generate Regular Expressions Online",
    howToHeading: "How to Generate a Regex",
    featuresHeading: "Regex Generator Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Structured templates",
      "Optional starts/ends/contains rules",
      "Copy generated regex",
      "Link to Regex Tester",
      "Clear template notices",
    ],
    howToSteps: [
      {
        title: "Choose a Template",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Adjust Options",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Test the Regex",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Are generated patterns perfect?",
        answer: "No. They are useful starting points for common cases.",
      },
      {
        question: "Can I test the result?",
        answer: "Yes. Use Test This Regex to open the Regex Tester.",
      },
      {
        question: "Can I customize character sets?",
        answer: "Yes. Choose the custom template.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Regex"],
    outputFormats: ["Regex"],
  }),
  tool({
    id: "base64-encoder",
    name: "Base64 Encoder",
    slug: "base64-encoder",
    category: "developer-tools",
    description: "Encode Unicode text to Base64 safely in your browser.",
    shortDescription: "Encode text to Base64.",
    icon: "code",
    keywords: [
      "base64 encoder",
      "encode base64",
      "text to base64",
    ],
    popular: true,
    new: false,
    supportedFormats: ["Text"],
    relatedToolIds: [
      "base64-decoder",
      "url-encoder",
      "url-decoder",
      "html-entity-encoder",
      "json-formatter",
    ],
    seoTitle: "Base64 Encoder — Encode Text to Base64 | ToolMyra",
    seoDescription: "Encode text to Base64 online with ToolMyra. Convert Unicode text into Base64 and copy or download the result.",
    h1: "Base64 Encoder",
    intro: "Convert text into Base64 using Unicode-aware encoding. This encodes text data — it is not encryption.",
    convertHeading: "Encode Text to Base64",
    howToHeading: "How to Encode Base64",
    featuresHeading: "Base64 Encoder Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Unicode-aware encoding",
      "Live conversion",
      "Copy and download",
      "Clear empty-input errors",
      "No account required",
    ],
    howToSteps: [
      {
        title: "Enter Your Text",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Encode to Base64",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Is Base64 encryption?",
        answer: "No. Anyone can decode Base64.",
      },
      {
        question: "Does Unicode work?",
        answer: "Yes. Text is encoded as UTF-8 bytes first.",
      },
      {
        question: "Is conversion live?",
        answer: "Yes.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Text"],
    outputFormats: ["Text"],
  }),
  tool({
    id: "base64-decoder",
    name: "Base64 Decoder",
    slug: "base64-decoder",
    category: "developer-tools",
    description: "Decode valid Base64 back into Unicode text with clear errors for invalid input.",
    shortDescription: "Decode Base64 to text.",
    icon: "code",
    keywords: [
      "base64 decoder",
      "decode base64",
      "base64 to text",
    ],
    popular: false,
    new: false,
    supportedFormats: ["Text"],
    relatedToolIds: [
      "base64-encoder",
      "url-decoder",
      "url-encoder",
      "html-entity-encoder",
      "json-formatter",
    ],
    seoTitle: "Base64 Decoder — Decode Base64 to Text | ToolMyra",
    seoDescription: "Decode Base64 online with ToolMyra. Convert valid Base64 into Unicode text and review clear errors for invalid input.",
    h1: "Base64 Decoder",
    intro: "Decode Base64 into UTF-8 text. Invalid Base64 or non-UTF-8 payloads produce a clear error instead of corrupted silent output.",
    convertHeading: "Decode Base64 to Text",
    howToHeading: "How to Decode Base64",
    featuresHeading: "Base64 Decoder Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Whitespace-tolerant input",
      "UTF-8 text decoding",
      "Clear invalid-input errors",
      "Live conversion",
      "Copy and download",
    ],
    howToSteps: [
      {
        title: "Paste Base64",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Decode to Text",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy or Download",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "What if Base64 is invalid?",
        answer: "Decoding stops with a clear error.",
      },
      {
        question: "Are spaces allowed?",
        answer: "Whitespace is ignored before decoding.",
      },
      {
        question: "Does it decode files?",
        answer: "This tool focuses on text Base64.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Text"],
    outputFormats: ["Text"],
  }),
  tool({
    id: "url-encoder",
    name: "URL Encoder",
    slug: "url-encoder",
    category: "developer-tools",
    description: "Encode text with URI component or full URI semantics for safe URL usage.",
    shortDescription: "Encode URI components safely.",
    icon: "code",
    keywords: [
      "url encoder",
      "encode url",
      "percent encode",
      "uri encode",
    ],
    popular: false,
    new: false,
    supportedFormats: ["Text"],
    relatedToolIds: [
      "url-decoder",
      "base64-encoder",
      "html-entity-encoder",
      "regex-generator",
      "find-and-replace",
    ],
    seoTitle: "URL Encoder — Encode URL Components Online | ToolMyra",
    seoDescription: "Encode URL components online with ToolMyra. Apply percent-encoding with clear URI component or full URI modes.",
    h1: "URL Encoder",
    intro: "Percent-encode text for safe use in URLs. Choose URI component mode for values, or full URI mode when encoding a broader URL string.",
    convertHeading: "Encode URL Components Online",
    howToHeading: "How to Encode a URL",
    featuresHeading: "URL Encoder Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "URI component mode",
      "Full URI mode",
      "Live encoding",
      "Copy and download",
      "Clear empty-input errors",
    ],
    howToSteps: [
      {
        title: "Enter Your Text",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Choose Encoding Mode",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Which mode should I use?",
        answer: "Use URI component for query values. Use full URI when encoding a broader URL string.",
      },
      {
        question: "Is encoding live?",
        answer: "Yes.",
      },
      {
        question: "Does it change already-encoded text?",
        answer: "Encoding applies to the current input as written.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Text"],
    outputFormats: ["Text"],
  }),
  tool({
    id: "url-decoder",
    name: "URL Decoder",
    slug: "url-decoder",
    category: "developer-tools",
    description: "Decode percent-encoded URL text safely and handle malformed sequences gracefully.",
    shortDescription: "Decode percent-encoded text.",
    icon: "code",
    keywords: [
      "url decoder",
      "decode url",
      "percent decode",
      "uri decode",
    ],
    popular: false,
    new: false,
    supportedFormats: ["Text"],
    relatedToolIds: [
      "url-encoder",
      "base64-decoder",
      "html-entity-encoder",
      "find-and-replace",
      "text-cleaner",
    ],
    seoTitle: "URL Decoder — Decode URL Encoding Online | ToolMyra",
    seoDescription: "Decode percent-encoded text online with ToolMyra. Convert sequences like %20 into readable characters safely.",
    h1: "URL Decoder",
    intro: "Decode percent-encoded text such as %20 back into readable characters. Malformed sequences produce a clear error instead of crashing.",
    convertHeading: "Decode URL Encoding Online",
    howToHeading: "How to Decode a URL",
    featuresHeading: "URL Decoder Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Percent-decoding",
      "Plus-to-space handling",
      "Graceful malformed-input errors",
      "Live decoding",
      "Copy and download",
    ],
    howToSteps: [
      {
        title: "Paste Encoded Text",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Decode the Text",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "What does %20 become?",
        answer: "A space.",
      },
      {
        question: "What if encoding is invalid?",
        answer: "A clear error is shown.",
      },
      {
        question: "Is decoding live?",
        answer: "Yes.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Text"],
    outputFormats: ["Text"],
  }),
  tool({
    id: "html-entity-encoder",
    name: "HTML Entity Encoder",
    slug: "html-entity-encoder",
    category: "developer-tools",
    description: "Encode special characters into HTML entities for safe source display without rendering HTML.",
    shortDescription: "Escape text as HTML entities.",
    icon: "code",
    keywords: [
      "html entity encoder",
      "encode html entities",
      "html escape",
      "escape html",
    ],
    popular: false,
    new: false,
    supportedFormats: ["Text"],
    relatedToolIds: [
      "html-formatter",
      "html-minifier",
      "url-encoder",
      "base64-encoder",
      "markdown-to-html",
    ],
    seoTitle: "HTML Entity Encoder — Escape HTML Characters | ToolMyra",
    seoDescription: "Encode HTML entities online with ToolMyra. Escape characters like <, >, and & for safe HTML source use.",
    h1: "HTML Entity Encoder",
    intro: "Convert special characters into HTML entities such as &lt; and &amp;. The result is shown as source text and is never rendered as HTML.",
    convertHeading: "Encode HTML Entities Online",
    howToHeading: "How to Encode HTML Entities",
    featuresHeading: "HTML Entity Encoder Features",
    supportedFormatsHeading: "Supported Formats",
    relatedToolsHeading: "Related Developer Tools",
    hideReport: true,
    processingMode: "browser",
    features: [
      "Escapes special HTML characters",
      "Predictable single-pass encoding",
      "Source-only display",
      "Live conversion",
      "Copy and download",
    ],
    howToSteps: [
      {
        title: "Enter Your Text",
        description: "Paste or type the content you want to process.",
      },
      {
        title: "Encode Entities",
        description: "Run the action or review the live result.",
      },
      {
        title: "Copy the Result",
        description: "Copy or download when you are ready.",
      },
    ],
    faq: [
      {
        question: "Will this render HTML?",
        answer: "No. Output is shown as escaped source text.",
      },
      {
        question: "Does it double-encode?",
        answer: "It encodes raw special characters in a single pass.",
      },
      {
        question: "Which characters are escaped?",
        answer: "&, <, >, quotes, and apostrophes.",
      },
      {
        question: "Private?",
        answer: "Yes.",
      },
    ],
    inputFormats: ["Text"],
    outputFormats: ["Text"],
  }),
];
