import type { CategoryId, ToolDefinition, ToolFaq } from "./types";

function makeTool(
  partial: Omit<ToolDefinition, "route" | "status"> & {
    status?: ToolDefinition["status"];
  },
): ToolDefinition {
  return {
    ...partial,
    route: `/tools/${partial.slug}`,
    status: partial.status ?? "available",
  };
}

function faqs(items: Array<[string, string]>): ToolFaq[] {
  return items.map(([question, answer]) => ({ question, answer }));
}

function steps(a: string, b: string, c: string) {
  return [
    { title: "Start", description: a },
    { title: "Adjust", description: b },
    { title: "Get the result", description: c },
  ];
}

function base(
  opts: {
    id: string;
    name: string;
    category: CategoryId;
    description: string;
    shortDescription: string;
    keywords: string[];
    relatedToolIds: string[];
    intro: string;
    features: string[];
    faq: ToolFaq[];
    icon?: string;
    popular?: boolean;
    aliases?: string[];
    exactPrimaryKeyword?: string;
    convertHeading?: string;
    howToHeading?: string;
    featuresHeading?: string;
    inputFormats?: string[];
    outputFormats?: string[];
    howTo?: ReturnType<typeof steps>;
  },
): ToolDefinition {
  return makeTool({
    id: opts.id,
    name: opts.name,
    slug: opts.id,
    category: opts.category,
    exactPrimaryKeyword: opts.exactPrimaryKeyword ?? opts.name.toLowerCase(),
    aliases: opts.aliases,
    description: opts.description,
    shortDescription: opts.shortDescription,
    icon: opts.icon ?? "text",
    keywords: opts.keywords,
    popular: opts.popular ?? false,
    new: true,
    supportedFormats: opts.inputFormats ?? ["Text"],
    relatedToolIds: opts.relatedToolIds,
    seoTitle: `${opts.name} — Free Online | Tool Base`,
    seoDescription: opts.description.length > 80 ? opts.description.slice(0, 155) : `${opts.description} Use this Tool Base utility without creating an account.`,
    h1: opts.name,
    intro: opts.intro,
    convertHeading: opts.convertHeading ?? opts.name,
    howToHeading: opts.howToHeading ?? `How to use ${opts.name}`,
    featuresHeading: opts.featuresHeading ?? `${opts.name} features`,
    relatedToolsHeading: "Related Tools",
    hideReport: true,
    processingMode: "browser",
    features: opts.features,
    howToSteps: opts.howTo ?? steps("Open the tool and add your input.", "Review the options and run the action.", "Copy or download the result."),
    faq: opts.faq,
    inputFormats: opts.inputFormats ?? ["Text"],
    outputFormats: opts.outputFormats ?? ["Text"],
  });
}

export const expansionTools: ToolDefinition[] = [
  base({
    id: "jpg-to-svg",
    name: "JPG to SVG",
    category: "image-tools",
    icon: "image-convert",
    description: "Trace a JPG or JPEG image into SVG vector paths for simple artwork and logos.",
    shortDescription: "Trace JPG images into SVG vector paths.",
    keywords: ["jpg to svg", "jpeg to svg", "jpg svg converter", "convert jpg to svg", "raster to vector"],
    relatedToolIds: ["png-to-svg", "svg-to-png", "jpg-to-png", "image-compressor"],
    intro: "Turn a JPG into SVG markup by tracing shapes. Simple logos convert more cleanly than photographs. The result is real SVG path data, not a renamed file extension.",
    features: ["Raster-to-vector tracing", "Downloads .svg markup", "Works with JPG and JPEG", "No account required"],
    faq: faqs([
      ["Is this a real vector conversion?", "Yes. The image is traced into SVG paths. Complex photos will look simplified."],
      ["Does it wrap the JPG inside an SVG?", "No. The download is traced vector markup, not an embedded bitmap wrapper."],
    ]),
    inputFormats: ["JPG", "JPEG"],
    outputFormats: ["SVG"],
  }),
  base({
    id: "image-to-webp",
    name: "Image to WebP",
    category: "image-tools",
    icon: "image-convert",
    description: "Convert JPG, PNG, GIF, BMP, or WebP images to the WebP format.",
    shortDescription: "Convert common images to WebP.",
    keywords: ["image to webp", "convert photo to webp", "jpg to webp", "png to webp", "webp converter"],
    relatedToolIds: ["jpg-to-webp", "png-to-webp", "webp-to-jpg", "image-compressor"],
    intro: "Upload a common raster image and download a WebP file. Animated GIFs use the first frame.",
    features: ["JPG, PNG, GIF, BMP, and WebP input", "WebP output", "First-frame GIF handling"],
    faq: faqs([
      ["Which formats can I upload?", "JPG, JPEG, PNG, GIF, BMP, and WebP."],
      ["Does animation survive?", "No. Still-image WebP is produced from the first frame."],
    ]),
    inputFormats: ["JPG", "PNG", "GIF", "BMP", "WebP"],
    outputFormats: ["WebP"],
  }),
  base({
    id: "image-to-base64",
    name: "Image to Base64",
    category: "image-tools",
    icon: "image",
    description: "Encode an image file as a Base64 data URL you can paste into HTML or CSS.",
    shortDescription: "Encode images as Base64 data URLs.",
    keywords: ["image to base64", "encode image base64", "data url image"],
    relatedToolIds: ["base64-to-image", "base64", "base64-file-converter", "png-to-jpg"],
    intro: "Choose an image and get a data URL. Copy it into CSS, HTML, or another tool. The original file is not overwritten.",
    features: ["Image upload", "Data URL output", "Copy result"],
    faq: faqs([
      ["What do I get back?", "A data URL beginning with data:image that includes the Base64 payload."],
      ["Is the original file changed?", "No. You download or copy a new encoded string."],
    ]),
    inputFormats: ["Image files"],
    outputFormats: ["Base64 data URL"],
  }),
  base({
    id: "base64-to-image",
    name: "Base64 to Image",
    category: "image-tools",
    icon: "image",
    description: "Preview and download an image from a Base64 data URL.",
    shortDescription: "Turn a Base64 data URL into an image preview.",
    keywords: ["base64 to image", "decode base64 image", "data url to png"],
    relatedToolIds: ["image-to-base64", "base64", "base64-decoder"],
    intro: "Paste a data URL that starts with data:image to preview the picture and download it.",
    features: ["Data URL paste", "Image preview", "Download"],
    faq: faqs([
      ["What input is accepted?", "A data URL that starts with data:image."],
      ["What if the payload is invalid?", "You will see an error instead of a fake image."],
    ]),
    inputFormats: ["Base64 data URL"],
    outputFormats: ["Image preview"],
  }),
  base({
    id: "invert-image-colors",
    name: "Invert Image Colors",
    category: "image-tools",
    icon: "image",
    description: "Invert the colors of a JPG, PNG, or WebP image and download the result.",
    shortDescription: "Invert image colors and download a new file.",
    keywords: ["invert image colors", "negative image", "invert photo colors"],
    relatedToolIds: ["black-and-white-image", "image-color-picker", "image-compressor"],
    intro: "Upload an image, invert its colors, and download a new file. The original upload stays unchanged.",
    features: ["Color inversion", "JPG, PNG, WebP", "Download a new file"],
    faq: faqs([
      ["Does this edit my original?", "No. A new image is created for download."],
      ["Which formats work?", "JPG, PNG, and WebP."],
    ]),
    inputFormats: ["JPG", "PNG", "WebP"],
    outputFormats: ["JPG", "PNG", "WebP"],
  }),
  base({
    id: "black-and-white-image",
    name: "Black and White Image",
    category: "image-tools",
    icon: "image",
    description: "Convert a color photo to grayscale and download the black-and-white result.",
    shortDescription: "Convert photos to black and white.",
    keywords: ["black and white image", "grayscale converter", "convert photo to grayscale"],
    relatedToolIds: ["invert-image-colors", "image-compressor", "image-quality-changer"],
    intro: "Turn a color image into grayscale. Useful for print drafts, documents, and visual tests.",
    features: ["Grayscale conversion", "JPG, PNG, WebP", "Download"],
    faq: faqs([
      ["Is color information kept?", "The download is grayscale. Keep the original if you still need color."],
      ["Can I undo?", "Use Reset and process the original file again."],
    ]),
    inputFormats: ["JPG", "PNG", "WebP"],
    outputFormats: ["JPG", "PNG", "WebP"],
  }),
  base({
    id: "meme-generator",
    name: "Meme Generator",
    category: "design-creative",
    icon: "image",
    description: "Add top and bottom captions to your own image and download a PNG meme.",
    shortDescription: "Caption your own image and download a PNG.",
    keywords: ["meme generator", "add text to image", "caption generator"],
    popular: true,
    relatedToolIds: ["text-to-image", "image-cropper", "image-resizer"],
    intro: "Upload your own picture, add top and bottom text, then download a PNG. Tool Base does not ship copyrighted meme templates.",
    features: ["Your own image", "Top and bottom text", "Adjustable size", "PNG download"],
    faq: faqs([
      ["Do you provide popular meme templates?", "No. Upload an image you have the right to use."],
      ["What file do I get?", "A PNG of the captioned image."],
    ]),
    inputFormats: ["Images you upload"],
    outputFormats: ["PNG"],
  }),
  base({
    id: "mhtml-to-pdf",
    name: "MHTML to PDF",
    category: "pdf-tools",
    icon: "pdf",
    description: "Extract HTML from an MHTML/MHT snapshot and save it as a PDF through your print dialog.",
    shortDescription: "Extract MHTML HTML and save it as PDF.",
    keywords: ["mhtml to pdf", "mht to pdf", "convert mhtml"],
    relatedToolIds: ["html-to-markdown", "txt-to-pdf", "markdown-to-pdf"],
    intro: "Upload an MHTML or MHT file. Tool Base extracts the HTML document and opens a print window so you can save a PDF. This is a print/export path, not a silent server conversion.",
    features: ["MHTML/MHT upload", "HTML extraction", "Print to PDF"],
    faq: faqs([
      ["Does this convert on a hidden server?", "No. Extracted HTML is opened so you can print or save as PDF."],
      ["What if the file has no HTML part?", "You will see an error. Nothing fake is generated."],
    ]),
    inputFormats: ["MHTML", "MHT"],
    outputFormats: ["PDF via print"],
  }),
  base({
    id: "bionic-reading-converter",
    name: "Bionic Reading Converter",
    category: "text-tools",
    description: "Emphasize the beginning of each word to create a bionic-style reading preview.",
    shortDescription: "Create a bionic-style reading preview.",
    keywords: ["bionic reading converter", "bionic reading", "guided reading text"],
    relatedToolIds: ["word-counter", "text-case-converter", "text-to-image"],
    intro: "Paste text and preview a reading style that bolds the start of each word. This is a reading aid, not a clinical treatment.",
    features: ["Live preview", "HTML copy", "Works on pasted text"],
    faq: faqs([
      ["Is this an official Bionic Reading product?", "No. It is an original Tool Base reading preview."],
      ["Can I copy the HTML?", "Yes. Use Copy HTML for the marked-up result."],
    ]),
  }),
  base({
    id: "unicode-to-krutidev",
    name: "Unicode to Krutidev",
    category: "text-tools",
    description: "Convert Devanagari Unicode text into a KrutiDev-style font encoding.",
    shortDescription: "Convert Unicode Devanagari to KrutiDev.",
    keywords: ["unicode to krutidev", "krutidev converter", "hindi unicode to kruti"],
    relatedToolIds: ["krutidev-to-unicode", "text-case-converter", "character-counter"],
    intro: "Paste Unicode Hindi/Devanagari text and convert it toward KrutiDev glyph codes used with legacy fonts. Rare conjuncts may still need a manual check.",
    features: ["Devanagari mapping", "Copy and download", "Legacy font workflow"],
    faq: faqs([
      ["Is every conjunct covered?", "Everyday characters are mapped. Unusual clusters may need review."],
      ["Which direction should I use?", "Use this tool from Unicode toward KrutiDev. Use Krutidev to Unicode for the reverse."],
    ]),
  }),
  base({
    id: "krutidev-to-unicode",
    name: "Krutidev to Unicode",
    category: "text-tools",
    description: "Convert KrutiDev-encoded Hindi text back into Unicode Devanagari.",
    shortDescription: "Convert KrutiDev text to Unicode.",
    keywords: ["krutidev to unicode", "kruti to unicode", "hindi font converter"],
    relatedToolIds: ["unicode-to-krutidev", "character-counter", "text-cleaner"],
    intro: "Paste KrutiDev-encoded text and convert it toward Unicode Devanagari so modern apps can display it.",
    features: ["Reverse mapping", "Copy and download", "Legacy document rescue"],
    faq: faqs([
      ["Will layout stay perfect?", "Character mapping is converted. Line layout still depends on the destination font."],
      ["What if the paste is mixed English?", "Latin characters pass through unchanged."],
    ]),
  }),
  base({
    id: "text-to-handwriting",
    name: "Text to Handwriting",
    category: "text-tools",
    icon: "text",
    description: "Render typed text in a handwriting-style image you can download as PNG.",
    shortDescription: "Turn typed text into a handwriting-style PNG.",
    keywords: ["text to handwriting", "handwriting generator", "cursive text image"],
    relatedToolIds: ["text-to-image", "meme-generator", "e-signature"],
    intro: "Type a note and download a handwriting-style PNG using original Tool Base rendering. No copyrighted school worksheets are included.",
    features: ["Cursive-style rendering", "Color controls", "PNG download"],
    faq: faqs([
      ["Is this a scanned font from a person?", "No. It uses a handwriting-style system font stack plus light variation."],
      ["Can I change colors?", "Yes. Background and text color are adjustable."],
    ]),
    outputFormats: ["PNG"],
  }),
  base({
    id: "random-object-generator",
    name: "Random Object Generator",
    category: "generators",
    description: "Generate a list of everyday object names for writing prompts, games, and mock content.",
    shortDescription: "Generate random everyday object names.",
    keywords: ["random object generator", "random items", "object list generator"],
    relatedToolIds: ["lorem-ipsum-generator", "random-string-generator", "randomize-list"],
    intro: "Create a list of ordinary object names. Useful for prompts, classroom games, and placeholder inventories.",
    features: ["Adjustable count", "Everyday vocabulary", "Copy the list"],
    faq: faqs([
      ["Are these product SKUs?", "No. They are generic object names for creative use."],
      ["Can I shuffle my own list instead?", "Use Randomize List for that."],
    ]),
  }),
  base({
    id: "text-to-image",
    name: "Text to Image",
    category: "text-tools",
    description: "Turn typed text into a downloadable PNG with size, color, and background controls.",
    shortDescription: "Render text as a PNG image.",
    keywords: ["text to image", "text png generator", "make image from text"],
    relatedToolIds: ["text-to-handwriting", "meme-generator", "image-resizer"],
    intro: "Write a line or a paragraph, choose colors and size, then download a PNG of the rendered text.",
    features: ["Font size", "Background and text color", "PNG download"],
    faq: faqs([
      ["Is this an AI image model?", "No. It draws your actual typed characters onto a canvas."],
      ["Does wrapping stay exact?", "Use line breaks in the editor for precise layout."],
    ]),
    outputFormats: ["PNG"],
  }),
  base({
    id: "randomize-list",
    name: "Randomize List",
    category: "text-tools",
    description: "Shuffle lines of a list into a new random order for draws, queues, and writing prompts.",
    shortDescription: "Shuffle list lines into a new order.",
    keywords: ["randomize list", "shuffle list", "randomize lines"],
    relatedToolIds: ["reverse-list", "sort-lines", "remove-duplicate-lines"],
    intro: "Paste one item per line and shuffle the order. Blank lines are kept in the shuffled result.",
    features: ["Line shuffle", "Copy and download", "Keeps each line intact"],
    faq: faqs([
      ["Is the shuffle repeatable?", "Each run uses a new random order."],
      ["Does it merge lines?", "No. Each line stays a separate item."],
    ]),
  }),
  base({
    id: "reverse-list",
    name: "Reverse List",
    category: "text-tools",
    description: "Reverse the order of lines in a list without changing the line contents.",
    shortDescription: "Reverse the order of list lines.",
    keywords: ["reverse list", "reverse lines", "flip list order"],
    relatedToolIds: ["randomize-list", "reverse-text", "sort-lines"],
    intro: "Paste a list and reverse it from last line to first. Words inside a line are not reversed.",
    features: ["Line order reverse", "Copy and download", "Leaves item text intact"],
    faq: faqs([
      ["Is this the same as Reverse Text?", "No. Reverse Text flips characters. Reverse List flips line order."],
      ["Are empty lines kept?", "Yes."],
    ]),
  }),
  base({
    id: "ip-to-binary",
    name: "IP to Binary",
    category: "security-encoding",
    icon: "code",
    description: "Convert an IPv4 address into four 8-bit binary octets.",
    shortDescription: "Convert IPv4 addresses to binary octets.",
    keywords: ["ip to binary", "ipv4 binary converter", "ip address binary"],
    relatedToolIds: ["binary-to-decimal", "text-to-binary", "random-ip-generator"],
    intro: "Enter an IPv4 address such as 192.0.2.10 and see each octet as 8-bit binary. This is a conversion helper, not a network lookup.",
    features: ["IPv4 parsing", "8-bit octets", "Copy the binary string"],
    faq: faqs([
      ["Does this look up DNS?", "No. It only converts the address you typed."],
      ["Is IPv6 supported?", "Not in this version. Use dotted IPv4."],
    ]),
  }),
  base({
    id: "ascii-to-text",
    name: "ASCII to Text",
    category: "text-tools",
    icon: "code",
    description: "Convert space-separated ASCII or Unicode code points back into text.",
    shortDescription: "Decode ASCII/Unicode code points to text.",
    keywords: ["ascii to text", "ascii decoder", "code points to text"],
    relatedToolIds: ["text-to-ascii", "text-to-binary", "hex-to-text"],
    intro: "Paste numbers such as 72 101 108 108 111 and convert them into characters. Hex values like 0x48 are accepted.",
    features: ["Decimal or hex codes", "Unicode code points", "Copy decoded text"],
    faq: faqs([
      ["What separators work?", "Spaces or commas."],
      ["Can I decode emoji?", "Yes, if you provide valid Unicode code points."],
    ]),
  }),
  base({
    id: "text-to-ascii",
    name: "Text to ASCII",
    category: "text-tools",
    icon: "code",
    description: "Show the Unicode code point of each character in your text.",
    shortDescription: "Convert text into Unicode code points.",
    keywords: ["text to ascii", "ascii encoder", "unicode code points"],
    relatedToolIds: ["ascii-to-text", "text-to-binary", "text-to-hex"],
    intro: "Type text and get a space-separated list of code points. Characters outside classic ASCII are included as Unicode numbers.",
    features: ["Code point list", "Copy and download", "Works beyond 7-bit ASCII"],
    faq: faqs([
      ["Is this only 0–127?", "Every character’s code point is listed, including values above 127."],
      ["How do I reverse it?", "Use ASCII to Text."],
    ]),
  }),
  base({
    id: "capitalize-words",
    name: "Capitalize Words",
    category: "text-tools",
    description: "Capitalize the first letter of each word in your text.",
    shortDescription: "Capitalize the first letter of each word.",
    keywords: ["capitalize words", "capitalized case", "capitalize each word"],
    relatedToolIds: ["title-case-converter", "uppercase-converter", "lowercase-converter"],
    intro: "Paste a sentence and capitalize every word. This is distinct from title case, which may leave small words lowercase.",
    features: ["Word capitalization", "Live conversion", "Copy and download"],
    faq: faqs([
      ["How is this different from Title Case?", "Title Case can skip short words. Capitalize Words capitalizes each word."],
      ["Are punctuation marks changed?", "Only letters at the start of words are capitalized."],
    ]),
  }),
  base({
    id: "sha384-hash",
    name: "SHA-384 Hash",
    category: "security-encoding",
    icon: "shield",
    description: "Generate a SHA-384 hash from text or a file. Hashes cannot be decrypted.",
    shortDescription: "Create SHA-384 hashes from text or files.",
    keywords: ["sha384 hash", "sha-384 generator", "sha384 checksum"],
    relatedToolIds: ["sha256-hash-generator", "sha512-hash-generator", "md5-hash-generator"],
    intro: "Hash text or a file with SHA-384. The digest is one-way. Tool Base will not offer a SHA-384 “decryptor.”",
    features: ["Text and file hashing", "Hex digest", "One-way hash notice"],
    faq: faqs([
      ["Can SHA-384 be decrypted?", "No. Cryptographic hashes are one-way."],
      ["Can I hash a file?", "Yes. Switch to file mode."],
    ]),
  }),
  base({
    id: "ripemd160",
    name: "RIPEMD-160",
    category: "security-encoding",
    icon: "shield",
    description: "Generate a RIPEMD-160 hash from text or a file. This is a one-way digest.",
    shortDescription: "Create RIPEMD-160 hashes from text or files.",
    keywords: ["ripemd160", "ripemd-160 hash", "ripemd generator"],
    relatedToolIds: ["sha1-hash-generator", "sha256-hash-generator", "md5-hash-generator"],
    intro: "Create a RIPEMD-160 digest for checksums and comparison. It cannot be reversed into the original input.",
    features: ["Text and file hashing", "Hex digest", "Clear one-way labeling"],
    faq: faqs([
      ["Is this encryption?", "No. It is a hash, not reversible encryption."],
      ["Should I use it for passwords?", "Prefer a modern password hashing scheme designed for that job."],
    ]),
  }),
  base({
    id: "aes-encrypt",
    name: "AES Encrypt",
    category: "security-encoding",
    icon: "shield",
    description: "Encrypt text with AES-256-GCM using a passphrase you choose.",
    shortDescription: "Encrypt text with AES-256-GCM.",
    keywords: ["aes encrypt", "aes-256", "encrypt text online"],
    relatedToolIds: ["aes-decrypt", "password-generator", "sha256-hash-generator"],
    intro: "Encrypt a message with AES-256-GCM. You need the same passphrase to decrypt. This is encryption, not hashing, and lost passphrases cannot be recovered.",
    features: ["AES-256-GCM", "Passphrase-derived key", "Copy the payload"],
    faq: faqs([
      ["Can you recover my passphrase?", "No. If it is lost, the payload stays unreadable."],
      ["Is a hash the same as this?", "No. Use AES Decrypt for this payload, not a hash tool."],
    ]),
  }),
  base({
    id: "aes-decrypt",
    name: "AES Decrypt",
    category: "security-encoding",
    icon: "shield",
    description: "Decrypt a Tool Base AES-256-GCM payload with the matching passphrase.",
    shortDescription: "Decrypt Tool Base AES-256-GCM payloads.",
    keywords: ["aes decrypt", "decrypt aes", "aes-256 decrypt"],
    relatedToolIds: ["aes-encrypt", "password-generator", "base64-decoder"],
    intro: "Paste a payload created by AES Encrypt and enter the passphrase. Wrong passphrases fail instead of inventing plaintext.",
    features: ["AES-256-GCM decrypt", "Passphrase check", "Copy plaintext"],
    faq: faqs([
      ["Will this decrypt SHA-256?", "No. Hashes are not encrypted messages."],
      ["What payload format is required?", "Output that starts with TB1. from AES Encrypt."],
    ]),
  }),
  base({
    id: "html-decode",
    name: "HTML Decode",
    category: "developer-tools",
    icon: "code",
    description: "Decode HTML entities such as &amp; and &#39; back into characters.",
    shortDescription: "Decode HTML entities into characters.",
    keywords: ["html decode", "html entity decoder", "decode html entities"],
    relatedToolIds: ["html-entity-encoder", "url-decoder", "base64-decoder"],
    intro: "Paste encoded HTML entities and convert them back to readable characters. The result is shown as text and is not executed as a page.",
    features: ["Named entities", "Numeric entities", "Live conversion"],
    faq: faqs([
      ["Does this run the HTML?", "No. Output is plain text."],
      ["What is the reverse tool?", "HTML Entity Encoder."],
    ]),
  }),
  base({
    id: "base64",
    name: "Base64 Encode/Decode",
    category: "developer-tools",
    icon: "code",
    description: "Encode text to Base64 or decode Base64 back to text in one utility.",
    shortDescription: "Encode or decode Base64 text.",
    keywords: ["base64", "base64 encode", "base64 decode", "base64 encoder decoder"],
    relatedToolIds: ["base64-encoder", "base64-decoder", "image-to-base64"],
    intro: "Switch between encode and decode for Base64 text. Invalid payloads return an error instead of invented output.",
    features: ["Encode and decode", "Copy result", "Invalid-input errors"],
    faq: faqs([
      ["Is Base64 encryption?", "No. It is encoding, not encryption."],
      ["Need image Base64?", "Use Image to Base64 or Base64 to Image."],
    ]),
  }),
  base({
    id: "json-viewer",
    name: "JSON Viewer",
    category: "developer-tools",
    icon: "code",
    description: "Inspect JSON in a collapsible tree with search and copy.",
    shortDescription: "Inspect JSON in a collapsible tree.",
    keywords: ["json viewer", "json tree", "inspect json"],
    relatedToolIds: ["json-formatter", "json-minifier", "json-validator", "json-to-xml"],
    intro: "Paste JSON to expand and collapse nodes, search values, and copy the source. Malformed JSON is reported instead of faked.",
    features: ["Tree view", "Search", "Expand and collapse", "Copy JSON"],
    faq: faqs([
      ["Does it execute JSON?", "No. It only displays structure."],
      ["What if the JSON is invalid?", "A parse error is shown."],
    ]),
    inputFormats: ["JSON"],
    outputFormats: ["Tree view"],
  }),
  base({
    id: "hex-to-rgb",
    name: "HEX to RGB",
    category: "developer-tools",
    icon: "code",
    description: "Convert HEX colors such as #155EEF into rgb() values.",
    shortDescription: "Convert HEX colors to RGB.",
    keywords: ["hex to rgb", "hex rgb converter", "color converter"],
    relatedToolIds: ["rgb-to-hex", "color-palette-generator", "css-gradient-generator"],
    intro: "Paste a 3- or 6-digit HEX color, with or without #, and get an rgb() string.",
    features: ["#RGB and #RRGGBB", "Live conversion", "Copy output"],
    faq: faqs([
      ["Are 8-digit HEX values supported?", "This version converts 3- and 6-digit HEX."],
      ["Need the reverse?", "Use RGB to HEX."],
    ]),
  }),
  base({
    id: "rgb-to-hex",
    name: "RGB to HEX",
    category: "developer-tools",
    icon: "code",
    description: "Convert rgb() or comma-separated RGB values into HEX.",
    shortDescription: "Convert RGB colors to HEX.",
    keywords: ["rgb to hex", "rgb hex converter", "color to hex"],
    relatedToolIds: ["hex-to-rgb", "color-palette-generator", "image-color-picker"],
    intro: "Enter rgb(21, 94, 239) or 21, 94, 239 and get a HEX color.",
    features: ["rgb() or comma input", "0–255 validation", "Copy HEX"],
    faq: faqs([
      ["What if a channel is 300?", "You will see an error. Channels must be 0–255."],
      ["Is alpha kept?", "Alpha in rgba() is ignored for HEX output in this version."],
    ]),
  }),
  base({
    id: "terms-generator",
    name: "Terms Generator",
    category: "generators",
    description: "Create a terms-of-use starter document with your organization details and clear placeholders.",
    shortDescription: "Draft a terms-of-use starter document.",
    keywords: ["terms generator", "terms of use generator", "terms and conditions template"],
    relatedToolIds: ["privacy-policy-generator", "html-boilerplate-generator", "meta-tags-generator"],
    intro: "Fill in organization name, website, and date to generate a starter terms document. It is a drafting aid, not legal advice.",
    features: ["Editable placeholders", "Copy and download", "Not legal advice"],
    faq: faqs([
      ["Is this legal advice?", "No. Have a qualified professional review anything you publish."],
      ["Can I ship this unchanged?", "No. Replace placeholders and review for your jurisdiction."],
    ]),
  }),
  base({
    id: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    category: "generators",
    description: "Create a privacy-policy starter with placeholders for vendors, retention, and choices.",
    shortDescription: "Draft a privacy-policy starter document.",
    keywords: ["privacy policy generator", "privacy policy template", "generate privacy policy"],
    relatedToolIds: ["terms-generator", "meta-tags-generator", "robots-txt-generator"],
    intro: "Generate a privacy-policy starter you can edit. List the vendors you actually use before publishing. This is not legal advice.",
    features: ["Organization fields", "Placeholder sections", "Copy and download"],
    faq: faqs([
      ["Does this make my site compliant automatically?", "No. Compliance depends on your real practices and the law that applies."],
      ["Do you include a contact email?", "No. Add a contact method only if you will monitor it."],
    ]),
  }),
  base({
    id: "random-ip-generator",
    name: "Random IP Generator",
    category: "utilities",
    icon: "code",
    description: "Generate synthetic IPv4 addresses in a documentation range for examples and tests.",
    shortDescription: "Generate synthetic IPv4 addresses for tests.",
    keywords: ["random ip generator", "fake ip generator", "test ipv4 addresses"],
    relatedToolIds: ["ip-to-binary", "random-number-generator", "uuid-generator"],
    intro: "Create synthetic IPv4 values in 203.0.0.0/16. They are documentation-style addresses, not live hosts and not a WHOIS or DNS lookup.",
    features: ["Synthetic IPv4", "Adjustable count", "Copy the list"],
    faq: faqs([
      ["Are these real public hosts?", "No. They are generated test values."],
      ["Does this query the internet?", "No."],
    ]),
  }),
  base({
    id: "webcam-test",
    name: "Webcam Test",
    category: "utilities",
    icon: "video",
    description: "Check camera permission, preview video, mirror the feed, and capture a snapshot.",
    shortDescription: "Preview your webcam and capture a snapshot.",
    keywords: ["webcam test", "camera test", "test webcam"],
    relatedToolIds: ["image-cropper", "image-compressor", "e-signature"],
    intro: "Start your camera, confirm the preview, optionally mirror it, and download a snapshot. If permission is denied, you will see a clear error.",
    features: ["Live preview", "Mirror toggle", "Snapshot PNG", "Permission error state"],
    faq: faqs([
      ["Is video uploaded?", "The preview stays in this page session. Snapshots download to your device."],
      ["What if I deny permission?", "The tool shows a permission error and does not invent a fake camera feed."],
    ]),
    inputFormats: ["Camera"],
    outputFormats: ["Preview", "PNG snapshot"],
  }),
  base({
    id: "corrupt-file",
    name: "Corrupt File",
    category: "utilities",
    icon: "text",
    description: "Create a deliberately altered copy of a file for parser and error-handling tests.",
    shortDescription: "Generate a corrupted test copy of a file.",
    keywords: ["corrupt file", "corrupt file generator", "broken file test"],
    relatedToolIds: ["random-string-generator", "base64-file-converter", "json-mock-data-generator"],
    intro: "Upload a file to download a new copy with random bytes changed. This is a diagnostic helper. The original file is never overwritten.",
    features: ["Original file unchanged", "New corrupted download", "Labeled as test data"],
    faq: faqs([
      ["Will this destroy my original?", "No. Only a new download is created."],
      ["Why would I use this?", "To test how an app handles damaged input."],
    ]),
    inputFormats: ["Any file"],
    outputFormats: ["Altered test copy"],
  }),
  base({
    id: "e-signature",
    name: "E-Signature",
    category: "design-creative",
    icon: "text",
    description: "Draw a signature, undo strokes, and download a transparent PNG.",
    shortDescription: "Draw a signature and download a PNG.",
    keywords: ["e-signature", "signature generator", "draw signature"],
    relatedToolIds: ["text-to-handwriting", "invoice-generator", "png-to-jpg"],
    intro: "Sign with a pointer or finger, undo if needed, and download a PNG with a transparent background. This does not apply a legally binding certificate.",
    features: ["Draw pad", "Undo and clear", "Pen thickness", "Transparent PNG"],
    faq: faqs([
      ["Is this a qualified electronic signature?", "It is a drawn image. Legal effect depends on your local rules and workflow."],
      ["Can I download it?", "Yes, as PNG."],
    ]),
    outputFormats: ["PNG"],
  }),
  base({
    id: "icons",
    name: "Icon Browser",
    category: "design-creative",
    icon: "image",
    description: "Browse Tool Base interface icons, search by name, and copy SVG markup.",
    shortDescription: "Search Tool Base icons and copy SVG.",
    keywords: ["icon browser", "svg icons", "copy svg icon"],
    relatedToolIds: ["svg-to-png", "png-to-svg", "web-templates"],
    intro: "Search the Tool Base icon set used across the site. Preview an icon and copy its SVG when you want the same mark in a draft.",
    features: ["Search", "Category labels", "Copy SVG"],
    faq: faqs([
      ["Whose icons are these?", "They are the original Tool Base interface set used on this site."],
      ["Can I copy SVG?", "Yes, from each card."],
    ]),
    outputFormats: ["SVG"],
  }),
  base({
    id: "web-templates",
    name: "Web Templates",
    category: "design-creative",
    icon: "code",
    description: "Copy original HTML starters for landings, portfolios, pricing, login, and dashboards.",
    shortDescription: "Copy original HTML page starters.",
    keywords: ["web templates", "html starter templates", "landing page html"],
    relatedToolIds: ["html-boilerplate-generator", "css-gradient-generator", "icons"],
    intro: "Download original Tool Base HTML starters. They are starting layouts, not copies of another site’s design.",
    features: ["Landing, portfolio, SaaS, pricing, navbar, hero, login, dashboard", "Copy or download HTML"],
    faq: faqs([
      ["Are these clones of another website?", "No. They are original starters."],
      ["Do they include a backend?", "No. They are static HTML you can restyle."],
    ]),
    outputFormats: ["HTML"],
  }),
  base({
    id: "invoice-generator",
    name: "Invoice Generator",
    category: "design-creative",
    icon: "calculator",
    description: "Fill in seller, customer, line items, tax, and discount, then print or save an invoice.",
    shortDescription: "Build an invoice and print or save it.",
    keywords: ["invoice generator", "create invoice", "invoice template"],
    relatedToolIds: ["e-signature", "vat-tax-calculator", "discount-calculator"],
    intro: "Enter business details and line items. The total uses your quantities, prices, discount, and tax. Print or save from the print dialog. There is no payment system.",
    features: ["Line items", "Tax and discount", "Print / save PDF", "No payments"],
    faq: faqs([
      ["Can customers pay here?", "No. This generator only prepares an invoice document."],
      ["How is the total calculated?", "Subtotal minus discount, then tax percentage."],
    ]),
    outputFormats: ["Print / PDF"],
  }),
];
