import {
  DEFAULT_DOC_MAX_BYTES,
  type DocumentDataConfig,
  type DocumentDataKind,
} from "./types";

function cfg(
  partial: Omit<DocumentDataConfig, "maxFileSizeBytes" | "notices"> &
    Partial<Pick<DocumentDataConfig, "maxFileSizeBytes" | "notices">>,
): DocumentDataConfig {
  return {
    maxFileSizeBytes: DEFAULT_DOC_MAX_BYTES,
    ...partial,
    notices: partial.notices ?? [],
  };
}

function make(
  slug: string,
  kind: DocumentDataKind,
  actionLabel: string,
  outputExtension: string,
  outputMime: string,
  accept: string,
  extensions: string[],
  mimeTypes: string[],
  extras: Partial<DocumentDataConfig> = {},
): DocumentDataConfig {
  return cfg({
    slug,
    kind,
    actionLabel,
    processingLabel: "Converting…",
    resetLabel: "Convert Another File",
    accept,
    extensions,
    mimeTypes,
    outputExtension,
    outputMime,
    filenameSuffix: "converted",
    inputMode: "file",
    ...extras,
  });
}

export const documentDataConfigs: Record<string, DocumentDataConfig> = {
  "docx-to-pdf": make(
    "docx-to-pdf",
    "docx-to-pdf",
    "Convert to PDF",
    "pdf",
    "application/pdf",
    ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ["docx"],
    ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    {
      notices: [
        "Complex DOCX features such as advanced layouts, macros, or embedded objects may not convert perfectly.",
      ],
    },
  ),
  "pdf-to-docx": make(
    "pdf-to-docx",
    "pdf-to-docx",
    "Convert to DOCX",
    "docx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".pdf,application/pdf",
    ["pdf"],
    ["application/pdf"],
    {
      notices: [
        "PDF is a fixed-layout format. Editable reconstruction is best-effort and may not match the original design. Scanned image-only PDFs need a text layer.",
      ],
    },
  ),
  "txt-to-pdf": make(
    "txt-to-pdf",
    "txt-to-pdf",
    "Convert to PDF",
    "pdf",
    "application/pdf",
    ".txt,text/plain",
    ["txt"],
    ["text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "Paste plain text here…",
    },
  ),
  "txt-to-docx": make(
    "txt-to-docx",
    "txt-to-docx",
    "Convert to DOCX",
    "docx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".txt,text/plain",
    ["txt"],
    ["text/plain"],
    { inputMode: "both", pastePlaceholder: "Paste plain text here…" },
  ),
  "docx-to-txt": make(
    "docx-to-txt",
    "docx-to-txt",
    "Extract Text",
    "txt",
    "text/plain;charset=utf-8",
    ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ["docx"],
    ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    { copyLabel: "Copy Text", filenameSuffix: "extracted" },
  ),
  "rtf-to-pdf": make(
    "rtf-to-pdf",
    "rtf-to-pdf",
    "Convert to PDF",
    "pdf",
    "application/pdf",
    ".rtf,application/rtf,text/rtf",
    ["rtf"],
    ["application/rtf", "text/rtf"],
  ),
  "rtf-to-txt": make(
    "rtf-to-txt",
    "rtf-to-txt",
    "Extract Text",
    "txt",
    "text/plain;charset=utf-8",
    ".rtf,application/rtf,text/rtf",
    ["rtf"],
    ["application/rtf", "text/rtf"],
    { copyLabel: "Copy Text", filenameSuffix: "extracted" },
  ),
  "markdown-to-html": make(
    "markdown-to-html",
    "markdown-to-html",
    "Convert to HTML",
    "html",
    "text/html;charset=utf-8",
    ".md,.markdown,text/markdown,text/x-markdown",
    ["md", "markdown"],
    ["text/markdown", "text/x-markdown", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "# Heading\n\nPaste Markdown here…",
      copyLabel: "Copy HTML",
    },
  ),
  "html-to-markdown": make(
    "html-to-markdown",
    "html-to-markdown",
    "Convert to Markdown",
    "md",
    "text/markdown;charset=utf-8",
    ".html,.htm,text/html",
    ["html", "htm"],
    ["text/html"],
    {
      inputMode: "both",
      pastePlaceholder: "<h1>Heading</h1>\n<p>Paste HTML here…</p>",
      copyLabel: "Copy Markdown",
    },
  ),
  "markdown-to-pdf": make(
    "markdown-to-pdf",
    "markdown-to-pdf",
    "Convert to PDF",
    "pdf",
    "application/pdf",
    ".md,.markdown,text/markdown",
    ["md", "markdown"],
    ["text/markdown", "text/x-markdown", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "# Heading\n\nPaste Markdown here…",
    },
  ),
  "csv-to-json": make(
    "csv-to-json",
    "csv-to-json",
    "Convert to JSON",
    "json",
    "application/json;charset=utf-8",
    ".csv,text/csv",
    ["csv"],
    ["text/csv", "application/csv", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "name,age,city\nJohn,25,Lahore",
      copyLabel: "Copy JSON",
    },
  ),
  "json-to-csv": make(
    "json-to-csv",
    "json-to-csv",
    "Convert to CSV",
    "csv",
    "text/csv;charset=utf-8",
    ".json,application/json",
    ["json"],
    ["application/json", "text/json", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: '[{"name":"John","age":25}]',
      copyLabel: "Copy CSV",
    },
  ),
  "csv-to-xml": make(
    "csv-to-xml",
    "csv-to-xml",
    "Convert to XML",
    "xml",
    "application/xml;charset=utf-8",
    ".csv,text/csv",
    ["csv"],
    ["text/csv", "application/csv", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "name,age\nJohn,25",
      copyLabel: "Copy XML",
    },
  ),
  "xml-to-json": make(
    "xml-to-json",
    "xml-to-json",
    "Convert to JSON",
    "json",
    "application/json;charset=utf-8",
    ".xml,application/xml,text/xml",
    ["xml"],
    ["application/xml", "text/xml"],
    {
      inputMode: "both",
      pastePlaceholder: "<root><item>value</item></root>",
      copyLabel: "Copy JSON",
    },
  ),
  "json-to-xml": make(
    "json-to-xml",
    "json-to-xml",
    "Convert to XML",
    "xml",
    "application/xml;charset=utf-8",
    ".json,application/json",
    ["json"],
    ["application/json", "text/json", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: '{"name":"John","age":25}',
      copyLabel: "Copy XML",
    },
  ),
  "txt-to-csv": make(
    "txt-to-csv",
    "txt-to-csv",
    "Convert to CSV",
    "csv",
    "text/csv;charset=utf-8",
    ".txt,text/plain",
    ["txt"],
    ["text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "John,25,Lahore\nSara,22,Karachi",
      copyLabel: "Copy CSV",
    },
  ),
  "csv-to-tsv": make(
    "csv-to-tsv",
    "csv-to-tsv",
    "Convert to TSV",
    "tsv",
    "text/tab-separated-values;charset=utf-8",
    ".csv,text/csv",
    ["csv"],
    ["text/csv", "application/csv", "text/plain"],
    { inputMode: "both", pastePlaceholder: "name,age\nJohn,25", copyLabel: "Copy TSV" },
  ),
  "tsv-to-csv": make(
    "tsv-to-csv",
    "tsv-to-csv",
    "Convert to CSV",
    "csv",
    "text/csv;charset=utf-8",
    ".tsv,text/tab-separated-values,text/tsv",
    ["tsv"],
    ["text/tab-separated-values", "text/tsv", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "name\tage\nJohn\t25",
      copyLabel: "Copy CSV",
    },
  ),
  "yaml-to-json": make(
    "yaml-to-json",
    "yaml-to-json",
    "Convert to JSON",
    "json",
    "application/json;charset=utf-8",
    ".yaml,.yml,text/yaml,application/x-yaml",
    ["yaml", "yml"],
    ["text/yaml", "application/x-yaml", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: "name: John\nage: 25",
      copyLabel: "Copy JSON",
    },
  ),
  "json-to-yaml": make(
    "json-to-yaml",
    "json-to-yaml",
    "Convert to YAML",
    "yaml",
    "text/yaml;charset=utf-8",
    ".json,application/json",
    ["json"],
    ["application/json", "text/json", "text/plain"],
    {
      inputMode: "both",
      pastePlaceholder: '{"name":"John","age":25}',
      copyLabel: "Copy YAML",
    },
  ),
};

export function getDocumentDataConfig(slug: string): DocumentDataConfig | undefined {
  return documentDataConfigs[slug];
}

export function isDocumentDataSlug(slug: string): boolean {
  return Boolean(documentDataConfigs[slug]);
}

export const documentDataSlugs = Object.keys(documentDataConfigs);
